### ISSUE TITLE
AnnData cannot open file that was opened with JHDF5 before

### ISSUE THREAD

**Issue by minnerbe** [scverse/anndata#1051]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

I noticed that AnnData throws an error while trying to read a `.h5ad` file that was opened with [JHDF5](https://unlimited.ethz.ch/display/JHDF/JHDF5+FAQ) (with write permissions) before. This means that AnnData is currently not able to open HDF5 files created from a Java program, even if the files conform to the [AnnData on-disk format](https://anndata.readthedocs.io/en/latest/fileformat-prose.html).

The problem most likely occurs because JHDF5 adds a `/__DATA_TYPES__` group (presumably for internal reasons), which can be seen by using `h5dump` before and after the access from Java and comparing with `diff`. AnnData tries to read that group, but fails because the datasets stored in this group have no valid AnnData-encoding type. I guess that this problem can be circumvented by making AnnData only read groups that are part of its on-disk schema, i.e., `X, layers, uns, obs[m|p], var[m|p]`.

### Steps to reproduce

This is a minimal python program failing on the last line if the file was opened from the Java-side in between write and read from the Python-side.

```python
import numpy as np
import anndata as ad

adata = ad.AnnData(np.zeros((2,2)))
adata.write('test.h5ad')

# There is a conditional error on this line:
# * without external interference: works
# * if opened with JHDF5 before: throws error
bdata = ad.read('test.h5ad')
```

Also, here is Java program causing the last line to fail. Note that it doesn't change the file, but just opens it with write permissions.

```java
import ch.systemsx.cisd.hdf5.HDF5Factory;

public class App {
	public static void main(String[] args) {
		HDF5Factory.open("test.h5ad");
	}
}
```
To get the necessary dependencies and execute the Java file, I suggest using maven with this `pom.xml`:

<details>

```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.scijava</groupId>
    <artifactId>pom-scijava</artifactId>
    <version>32.0.0-beta-5</version>
    <relativePath />
  </parent>

  <groupId>mwe</groupId>
  <artifactId>mwe</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>cisd</groupId>
      <artifactId>jhdf5</artifactId>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
	  <id>scijava.public</id>
  	  <url>https://maven.scijava.org/content/groups/public</url>
	</repository>
  </repositories>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.1</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```

</details>

### Traceback

<details>

```pytb
Traceback (most recent call last):
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 202, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 230, in read_elem
    read_func = self.registry.get_reader(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 143, in get_reader
    raise IORegistryError._from_read_parts(
anndata._io.specs.registry.IORegistryError: No read method registered for IOSpec(encoding_type='', encoding_version='') from <class 'h5py._hl.datatype.Datatype'>. You may need to update your installation of anndata.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 243, in read_h5ad
    adata = read_dispatched(f, callback=callback)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/experimental/__init__.py", line 58, in read_dispatched
    return reader.read_elem(elem)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 204, in func_wrapper
    re_raise_error(e, elem)
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 185, in re_raise_error
    raise e
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 202, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 235, in read_elem
    return self.callback(read_func, elem.name, elem, iospec=get_spec(elem))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 224, in callback
    **{
      ^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 227, in <dictcomp>
    k: read_dispatched(elem[k], callback)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/experimental/__init__.py", line 58, in read_dispatched
    return reader.read_elem(elem)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 204, in func_wrapper
    re_raise_error(e, elem)
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 185, in re_raise_error
    raise e
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 202, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 235, in read_elem
    return self.callback(read_func, elem.name, elem, iospec=get_spec(elem))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/h5ad.py", line 241, in callback
    return func(elem)
           ^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/specs/methods.py", line 94, in read_basic
    return {k: _reader.read_elem(v) for k, v in elem.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/specs/methods.py", line 94, in <dictcomp>
    return {k: _reader.read_elem(v) for k, v in elem.items()}
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 204, in func_wrapper
    re_raise_error(e, elem)
  File "/home/innerbergerm@hhmi.org/Software/mambaforge/envs/anndata/lib/python3.11/site-packages/anndata/_io/utils.py", line 188, in re_raise_error
    raise AnnDataReadError(
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/__DATA_TYPES__/Enum_Boolean' of type <class 'h5py._hl.datatype.Datatype'> from /.
```

</details>

### Versions

```python
anndata             0.9.1
session_info        1.0.0
-----
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
Linux-5.19.0-46-generic-x86_64-with-glibc2.35
-----
Session information updated at 2023-07-11 05:25
```

**Comment by ivirshup** [comment]
I can reproduce with:

```python
import anndata as ad, numpy as np, h5py

a = ad.AnnData(np.ones((5, 5)))
a.write("tmp.h5ad")

with h5py.File("tmp.h5ad", "w") as f:
    f.create_group("__DATA_TYPES__")

ad.read_h5ad("tmp.h5ad")
```

You can get around this right now with:

```python
with h5py.File("tmp.h5ad", "r") as f:
    result = ad.experimental.read_elem(f)
```

**Comment by ivirshup** [comment]
> It would be great, though, if this could be the default behavior in future versions to facilitate collaboration across language boundaries.

Is this a common feature in java hdf5 readers? It seems like there are multiple (like JHDF), and it's not easy for me to judge their popularity.

> even if the files conform to the [AnnData on-disk format](https://anndata.readthedocs.io/en/latest/fileformat-prose.html).

The specification says which entries are required, and a number of entries that MAY be included. It doesn't say you can put other entries in the anndata group, though it also doesn't specifically say you can't.

This should probably be clarified. Though the which direction the clarification goes would need some thought and consideration. I don't think [netcdf](https://docs.unidata.ucar.edu/netcdf-c/current/interoperability_hdf5.html#reading_with_hdf5) would be permissive about this, for example.

-----

> Does this being in the ad.experimental namespace mean that this is already planned for a future release?

Not neccesarily, but `read_elem` and `write_elem` will definitely move to the permanent API. However, `read_elem` should basically do the same thing as `read_h5ad` for new enough file formats.

**Comment by minnerbe** [comment]
> Is this a common feature in java hdf5 readers? It seems like there are multiple (like JHDF), and it's not easy for me to judge their popularity.

To be honest, my experience with HDF5 readers in Java is pretty limited, too, and it's not clear to me how wide-spread this behavior is. However, the particular library I'm using is featured on the [website of the HDF group](https://portal.hdfgroup.org/display/HDF5/HDF5+Language+Bindings) and is a wrapper around the official Java-bindings. Furthermore, also the [HDF5 version](https://github.com/saalfeldlab/n5-hdf5) of the [N5 API](https://github.com/saalfeldlab/n5) uses this particular library, so there is definitely a non-vanishing number of users potentially affected by this issue.

> The specification says which entries are required, and a number of entries that MAY be included. It doesn't say you can put other entries in the anndata group, though it also doesn't specifically say you can't.

I agree that this needs clarification. However, for the reasons above, providing a means of reading files with a `__DATA_TYPES__` group would be beneficial.

> Not neccesarily, but read_elem and write_elem will definitely move to the permanent API. However, read_elem should basically do the same thing as read_h5ad for new enough file formats.

Awesome! I expect that most files that are affected by this issue will conform to a sufficiently recent file format such that `read_elem` provides a viable solution.

**Comment by ivirshup** [comment]
I don't think any recent version of anndata would have allowed reading this file, so I'm hesitant to change that precedent.

Do you think you could confirm if the `n5` implementation has this behavior? I'd thought that people had made anndata readers/ writers using n5 (though possibly only the zarr format) and this hasn't come up before.

**Comment by flying-sheep** [comment]
I think it would be fine to ignore things like `__dunder__` or `.dotfile` groups in `/`. Not saying we should, but maybe.

That’s because `/X`, `/obs`, … are our (limited) entry points. We’ll never start adding arbitrary things in `/`. But deeper inside the structure, groups actually mean things like dicts stored in `uns` or so, so users adding things there means something and IO should definitely complain when there’s groups without metadata there.

**Comment by minnerbe** [comment]
> Do you think you could confirm if the n5 implementation has this behavior? I'd thought that people had made anndata readers/ writers using n5 (though possibly only the zarr format) and this hasn't come up before.

Implementing AnnData readers/writers using N5 is exactly where I'm coming from (as I said, N5 is using JHDF5 for it's HDF5 implementation), so I can confirm this. The reason why this hasn't come up earlier is a grossly negligent lack of testing on my side: I only properly tested Python -> Java and Java -> Java, where '->' means '-generated files can be read from'.

> edit: Actually it's not totally clear to me if the n5 library is a good point of reference, since it has it's own data model.

I agree. But that applies to the storage format (which, confusingly, is also named N5). I'm only using the N5 API to read/write HDF5 and Zarr.

Don't get me wrong, I can see the pitfalls of allowing arbitrary data in AnnData files and I don't think this should be the default behavior. Even generally allowing `__*__` or `.*` is perhaps not a good idea.
I'm just asking for a 'Java-switch' which recognizes and ignores this particular group. For the time being, the prospect of having a non-experimental way (i.e., `h5py` and `read_elem`) of reading these files is already sufficient to me.

**Comment by flying-sheep** [comment]
Hm, unfortunately, it’s configurable too: [`IHDF5WriterConfigurator.houseKeepingNameSuffix(String)`](https://openbis.ch/javadoc/jhdf5/19.04.1/ch/systemsx/cisd/hdf5/IHDF5WriterConfigurator.html#houseKeepingNameSuffix-java.lang.String-)

**Comment by minnerbe** [comment]
Oh, that's not good news. Thanks for digging into the code that deeply. I guess that ignoring the standard names would be sufficient.

**Comment by ivirshup** [comment]
I wouldn't want to special case a specific hdf5 implementation. But I think this sort of case would be covered by the aforementioned "permissive reader", though that wouldn't be the default behavior. I think an interim fix would be warning very loudly about this, saying it will error by default in the future, but allowing it.

@minnerbe (or maybe @bogovicj), do you have any sense of whether this behavior could be changed on the n5 side? Also what does this do?

**Comment by bogovicj** [comment]
> unfortunately, it’s configurable too: [IHDF5WriterConfigurator.houseKeepingNameSuffix(String)](https://openbis.ch/javadoc/jhdf5/19.04.1/ch/systemsx/cisd/hdf5/IHDF5WriterConfigurator.html#houseKeepingNameSuffix-java.lang.String-)

nasty. 

> whether this behavior could be changed on the n5 side

Perhaps.  It's strange, because jhdf5 seems to create that group immediately when making a writer.  Strange...
I think [this line](https://sissource.ethz.ch/sispub/jhdf5/-/blob/master/source/java/ch/systemsx/cisd/hdf5/HDF5BaseReader.java#L186) triggers the creation of that group, and I'm not immediately seeing any flags or other way to disable that.  

> Also what does this do?

Not clear (to me).  We can certainly read h5 data without the `__DATA_TYPES__` group, so its not essential.  I suppose we could just manually delete the group for the AnnData h5's we create, but I don't know what the consequences will be if any.

**Comment by minnerbe** [comment]
> Also what does this do?

I'm not sure either. It looks like it's trying to consolidate some data type meta-information  into a single place. Other HDF5 implementations seem to be able to read it, but it doesn't look essential.

> But I think this sort of case would be covered by the aforementioned "permissive reader", though that wouldn't be the default behavior. 

I think having a permissive-mode reader is a very viable long-term solution. For now, having a means of reading such files with `[experimental.]read_elem` is fine, I think.

Another possible (albeit very laborious and invasive) long-term approach would be to try to switch out JHDF5 in N5 for some other HDF5 Java bindings, since it seems like JHDF5 is not actively maintained right now. What's your take on this @bogovicj?

**Comment by flying-sheep** [comment]
> it seems like JHDF5 is not actively maintained right now

seems like you eventually want to get rid of it, and until then a stopgap solution dealing with its quirks right now (either on your side by deleting the groups or our side by ignoring it) is viable.

**Comment by ivirshup** [comment]
> I suppose we could just manually delete the group for the AnnData h5's we create

It looks like some other users of this library do that:

* https://github.com/DeplanckeLab/ASAP/blob/23dbabf6281b7dc3c5c4c97ff172687a5937a232/Java/src/hdf5/loom/LoomFile.java#L1012

But searching for ["`hdf5 __DATA_TYPES__`"](https://github.com/search?q=hdf5+__DATA_TYPES__&type=code) mostly looks like people trying to work around this being added.

**Comment by bogovicj** [comment]
>  try to switch out JHDF5 in N5 for some other HDF5 Java bindings, since it seems like JHDF5 is not actively maintained right now.

certainly possible.  There would have to be a pretty compelling reason, and I'm not sure that this (unwanted `__DATA_TYPES__` group) is enough to justify the effort.  Lack of maintenance eventually might be enough of a reason though - if there are clearly better alternatives.

**Comment by minnerbe** [comment]
Since there are some viable options to circumvent this problem (reading with a lower level API from AnnData or just deleting the group after writing from Java), I'm going to close this issue.
Thanks for your help!
