### ISSUE TITLE
Stop tests from writing files everywhere

### ISSUE THREAD

**Issue by flying-sheep** [scverse/anndata#1060]
### Please describe your wishes and possible alternatives to achieve the desired result.

AnnData’s tests are not well behaved and write `test.h5ad` and other things into the work directory.

We should set the working directory to read only in CI during test runs to prevent this.

**Comment by ivirshup** [comment]
If you want to enforce this, I would rather it was also enforced during local test runs. I don't think the test suite should behave that differently on CI vs local.

**Comment by flying-sheep** [comment]
That could be possible by having an `autouse` function that `cd`s into a temporary path before executing every single test. And that would make things behave differently in tests than otherwise (e.g. `sc.datasets.*()` will write to a different directory.

Another option is to check after each test if `git status --untracked-files` returns a different set of lines before and after the test run, but I don’t feel good about this one: if would make tests pass locally, and it involves a lot of file system interaction.

If you can think of another way or think the downsides of the other approaches aren’t that bad, I’m happy to explore it, but if not, that’s the best compromise I could come up with.

**Comment by martinkim0** [comment]
Not sure if this is a solution that would work with the AnnData test suite, but what we have set up in scvi-tools is a [pytest fixture](https://github.com/scverse/scvi-tools/blob/main/tests/conftest.py#L71-L78) that creates a temporary directory for every test function that has the `save_path` argument. This directory is deleted after the test finishes running, so we avoid accumulating test datasets in the working directory.

**Comment by flying-sheep** [comment]
That would swallow accidentally output files. My goal is to make sure nothing writes files that shouldn’t.
