### ISSUE TITLE
Cupy support in anndata

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1080]
Splitting out from:

* https://github.com/scverse/anndata/issues/355

Mostly implemented in 

* https://github.com/scverse/anndata/pull/1066

Opening this issue to discuss what else is needed for cupy support in anndata.

## Priority follow up

- [x] "How to" example of usage

## Other

- ~[ ]~ "How to" example of direct GPU IO Now opened as #1154
- [x] Look into refactoring for more array-api support
  - Looked into, we should probably do that

**Comment by Intron7** [comment]
> Is this in the case where the scipy matrix has 64 bit index types? I think this would make sense there.

Yes there are 64 bit indptr for scipy matrices. If you go above the limit the indptr will become negative and you run into issues with converting the matrix etc. 

> What would this do? I was hoping that it would let us move things between CPU and GPU, but I don't think that's consistent with the semantics of cupy and numpy. Maybe it can be handled on the array level for now?

Indeed, we could let the user handle this, and the syntax would likely be more similar to pytorch. I really came to like a simple oneliner that moves everything over to RAM and not manually converting every layer.

> For now could this just be "whether it's a cupy type or not"? I don't think I'd want to add a property to the AnnData object for this if you can do isinstance.

Using `isinstance` is entirely sufficient. I was just considering the scenario where someone wants to run a scanpy function on GPU AnnData or an rsc function with a scipy matrix. I'm currently making all my rapids-singlecell functions compatible with CPU AnnData and was contemplating such a flag.

**Comment by Intron7** [comment]
@ivirshup I have a PR (https://github.com/scverse/rapids_singlecell/pull/42) ready to go once the anndata 0.10.0 comes out. The only things I'll have to do is rerun the notebooks with benchmarks and depreciate cunndata and change the docs with the usage principle. So I think I can have the updated out at most 2 days after you publish.

**Comment by flying-sheep** [comment]
That’s awesome!

**Comment by ivirshup** [comment]
I'll split the others off into new issues, but will point to rapids-single cell for usage examples. Almost closable

**Comment by Intron7** [comment]
You can point to the documentation notebooks in https://rapids-singlecell.readthedocs.io/en/latest/notebooks.html
