### ISSUE TITLE
Define expected result from mixed device operations

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1083]
### Please describe your wishes and possible alternatives to achieve the desired result.

What is the expected result from concatenating an array stored on GPU, and one stored on CPU? Options are:

* We move data between devices, and decide on a default
* We error

What's the right choice here? I would think that a conservative approach is good to start. WDYT @Intron7?

**Comment by Intron7** [comment]
I think erroring might be a safe option. I think the best option IMO would be an argument, that defaults to CPU but you can you can tell it GPU if you know you have enough VRAM.

**Comment by ivirshup** [comment]
Right now `concat` supports concatenating CPU and GPU sparse arrays by moving the CPU array to GPU. This should be changed before a release.
