### ISSUE TITLE
Make checking var_names and obs_names for uniqueness optional

### ISSUE THREAD

**Issue by niklasmueboe** [scverse/anndata#1112]
By default when creating a new AnnData instance in the `_init_as_actual` function both `var_names` and `obs_names` are checked for uniqueness. When working with AnnData objects with several million `obs`/`var` this can become a performance limiting factor taking multiple seconds or even minutes.

Making the uniqueness check optional would allow the user the option to skip it when instantiating a new AnnData object e.g. via `ad.AnnData(X=X, ... , check_unique=False)`. This could be useful to improve performance especially when the input data is already guaranteed to have unique `obs_names` and `var_names.`

This was originally raised (with an example implementation) as a PR #1081

**Comment by niklasmueboe** [comment]
In my case I sometimes have up to ~200M `obs` (`var` is irrlevant in comparison) and then uniqueness checks can take around 2 mins.

I wasn't aware of the fact that pandas does uniquenesss checks when label-indexing anyway, and deferring the uniqueness check than would not necessary be beneficial (at least in my use case), because the computation will be done sooner or later.

I think that as long as pandas does not offer a solution for this (i.e. some public API for uniqueness guarantees) finding a real solution might be tricky.

Sidenote:
The issue partially arises due to the fact that only string indices are allowed while natively a MultiIndex of integers would be more suitable for me (and much faster, although not perfect). But I guess getting MultiIndex support might be even harder?

**Comment by niklasmueboe** [comment]
> Integer values as indices is particularly hard because it's ambiguous with positional indexing (as discussed in previous issues on this topic). I have been wondering about having a 'label-less' dimension, where only positional indexing is allowed.

For MultiIndexes the disambiguation could be made by only allowing tuples for slicing i.e. `adata[1, :]` would be assumed to be positional indexing and `adata[(1,), :]` would be "label-based" MultiIndex of Integers. But I understand the problems. Especially because in pandas `df.loc[1, :]` is also allowed as label-based indexing.

**Comment by flying-sheep** [comment]
Fixed in #1507
