### ISSUE TITLE
Drop python 3.8 support

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1116]
### Please describe your wishes and possible alternatives to achieve the desired result.

We're well past the window for python 3.8 support (https://scientific-python.org/specs/spec-0000/#support-window), so we should drop it for the next version.

**Comment by ivirshup** [comment]
@flying-sheep, seems like a PR you might wanna make?

**Comment by flying-sheep** [comment]
next version will be 0.10? no patch release?

then we could just bump the version, add Ruff’s `"UP"` rules and have Ruff handle most things for us.
