### ISSUE TITLE
Demo showing how to create a AnnData containing a dask array with sparse chunks

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1133]
### Please describe your wishes and possible alternatives to achieve the desired result.

Current WIP (Interrupted by: https://github.com/scverse/anndata/pull/1131) viewable here: https://gist.github.com/ivirshup/3fbe634b648304978ea77469b5d88961

**Comment by ilan-gold** [comment]
This has largely been done: https://scanpy.readthedocs.io/en/stable/tutorials/experimental/dask.html

This demo should be updated to use the latest `read_elem_as_dask` once it is released: https://github.com/scverse/anndata/pull/1469

**Comment by flying-sheep** [comment]
Re-opening as a reminder that we need to update the submodule and do a scanpy patch release so people can see the updates.
