### ISSUE TITLE
Postpone dtype deprecation

### ISSUE THREAD

**Issue by gtca** [scverse/anndata#1137]
### Please describe your wishes and possible alternatives to achieve the desired result.

As v0.8 has been recommending to use `dtype` in the constructor (`FutureWarning: X.dtype being converted to np.float32 from int64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass AnnData(X, dtype=X.dtype, ...) to get the future behavour.`), it might make the process a bit more gentle if the breaking changes associated with constructor arguments deprecation (https://github.com/scverse/anndata/pull/1126) can be postponed to a later release.

**Comment by ivirshup** [comment]
I would be up for this. I think having at least 2 feature releases/ or a year between deprecating a breaking change and making it is reasonable. It's only been 6 months since 0.9.

I will leave this open for a little more feedback, but am leaning towards postponing at the moment.
