### ISSUE TITLE
Error while writing annData

### ISSUE THREAD

**Issue by mari-ga** [scverse/anndata#1143]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [X] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

Hi Everyone, 
First of all, thank you very much for this wonderful tool. 
I'm reopening an issue, which seems to have affected other users. Such as [https://github.com/scverse/anndata/issues/726](#726). 
I created an Anndata object based on RNA and HTO data for hashing demultiplexing. No problem there, however when I try to to add the results from demultiplexing I run in the already seen: 

```
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'bff' of <class 'h5py._hl.group.Group'> to /
```

I opened a csv file as a dataframe, which contains the results from demultiplexing with BFF. The results look like this:
Barcode                            | BFF
TTTGTCATCTTACCTA-1 | negative
TTTGTCATCTTAGAGC-1 | negative
TTTGTCATCTTAGCCC-1 | HTO_BBX-1
TTTGTCATCTTATCTG-1 | negative
TTTGTCATCTTCAACT-1 | negative
TTTGTCATCTTCATGT-1 | negative
TTTGTCATCTTCCTTC-1 | negativ

Which is pretty standard for demultiplexing results.

The code throwing this error is:
Code:

```python
import scanpy as sc
import pandas as pd
from mudata import MuData
import numpy as np

rna_data = sc.read_10x_mtx("/path/raw/rna_raw_matrix")
data = pd.read_csv("bff_assignment.csv")
rna_data.obs = rna_data.obs.merge(data, left_index=True, right_index=True, how='left')
rna_data.obs.rename(columns={rna_data.obs.columns[0]: 'donor'}, inplace=True)
rna_data.obs.donor = rna_data.obs.donor.fillna("negative")
rna_data.obs.donor = rna_data.obs.donor.astype(str)

# code creating the error:
rna_data.write("/bff/adata.h5ad")

```

The error looks like this:
```
Traceback (most recent call last):
File "/Users/me/miniconda3/envs/summary/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 166, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 283, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 444, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 95, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 249, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings


  File "/Users/ne/miniconda3/envs/summary/lib/python3.9/site-packages/anndata/_io/utils.py", line 229, in re_raise_error
    raise type(e)(
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'bff' of <class 'h5py._hl.group.Group'> to /
```

I would appreciate any assistance you could provide. 
Thank you very much in advance!

### Versions

anndata             0.9.2
mudata              0.2.3
numpy               1.24.4
pandas              2.0.3
scanpy              1.9.3
session_info        1.0.0

**Comment by c-westhoven** [comment]
#1141 also has this issue

**Comment by ivirshup** [comment]
It looks like the problematic column (`bff`) isn't being converted to string, while your code is doing some work to cover the column `"donor"`.

I would suggest trying something like: `adata.obs["bff"] = adata.obs["bff"].astype("category")` before writing.

**Comment by c-westhoven** [comment]
@ivirshup Is there a better way of doing this? 
I'm testing functions that are new to me, so I don't always know whether columns are added to .obs/.var. And especially because some of the processing time is quite lengthy, it's quite annoying to have to re-run due to this TypeError. 

Additionally just saving everything as a category isn't always useful, since some "object" type columns are actually int/float columns. So I need to go through each column and check whether they are better saved as categories or floats/int before saving.

**Comment by mari-ga** [comment]
@ivirshup Thank you very much it worked!
