### ISSUE TITLE
Extend documentation on Zarr AnnData disk storage format

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/anndata#1155]
Following discussions on table support and the recent closure of the NGFF table spec PR, it's been noted that there isn't an "official" source detailing the AnnData disk storage specifically for the Zarr format to the needed extent.

While the current AnnData documentation has a section on disk storage, it provides a broad overview without specific focus on Zarr. 

Given that developers, especially those less familiar with Python, could greatly benefit from such a resource, it's suggested to add a new section, possibly on this page: https://anndata.readthedocs.io/en/latest/fileformat-prose.html. This section could lay out the Zarr format's tree-structure, or include scripts demonstrating how to retrieve some complex, representative example datasets.

A possibility would be to use [sphinx-tabs](https://github.com/executablebooks/sphinx-tabs) and have a tab showing HDF5 and one showing Zarr.

This would essentially help in formalizing and standardizing the Zarr AnnData format, making it more accessible and comprehensible.

CC @ivirshup @joshmoore

*Note: message co-written with ChatGPT.*

**Comment by ivirshup** [comment]
Added in #1162. Do you think you'd be able to take a look tonight?
