### ISSUE TITLE
Move `read_elem`, `write_elem` from experimental into main API

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1158]
### Please describe your wishes and possible alternatives to achieve the desired result.

`read_elem`, `write_elem` are stable enough to moved out of experimental.

Possible end locations include:

* Main namespace: `ad.read_elem`
* `io` submodule: `ad.io.read_elem`
* `storage` submodule `ad.storage.read_elem`

I'd like to make an `io` module for all the read and write functions, but maybe a new module that would also house other on disk access (e.g. `sparse_dataset`) would also be good.

**Comment by flying-sheep** [comment]
> but maybe a new module that would also house other on disk access (e.g. sparse_dataset) would also be good.

why wouldn’t that be able to go into a module called `anndata.io`?
