### ISSUE TITLE
Redo branch protections to allow creating new release branches

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1167]
Creation of new backport branches is blocked by the current rule sets.

I believe @flying-sheep switched the repo from branch protections to rule sets, because branch deletion rules got applied to meeseeks backport branches. 

I *think* we had avoided this problem previously by not protecting branches from deletion.

I've temporarily worked around this by just turning off the repo rules before pushing up the 0.10.x branch.

**Comment by ivirshup** [comment]
Hmm...

* https://github.com/scverse/anndata/pull/1166#issuecomment-1750537266

**Comment by ivirshup** [comment]
I'm not seeing a readthedocs check for main, but we are definitely doing builds on main... Maybe that's related?

**Comment by flying-sheep** [comment]
Hm, readthedocs probably doesn’t run as a GitHub check on main. Their PR builds were introduced later, so the “regular” builds probably don’t get reported back to GitHub.

I assume that it’s somehow this ruleset being responsible: https://github.com/scverse/anndata/settings/rules/87619. “Require status checks to pass before merging” does have the listed checks 1. pipelines (which reports check results on main) and 2. rtd (which doesn’t).

Seems like for rulesets, “Require status checks to pass before merging” actually means “Require status checks to pass before merging or pushing a new branch”

**Comment by flying-sheep** [comment]
Should be fixed since GitHub introduced the third checkbox here:

![grafik](https://github.com/user-attachments/assets/dc35cff1-1d17-46cd-ae4b-9efbc960d8a0)
