### ISSUE TITLE
Keep around a deprecated SparseDataset class for this release cycle

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1184]
Removal of the SparseDataset class from `anndata._core.sparse_dataset.SparseDataset` has caused issues for some downstream packages including scvi-tools.

We should probably at least give a deprecation for this, since it sees some use: https://github.com/search?q=from+anndata._core.sparse_dataset+import+SparseDataset&type=code

To do this we should export a `SparseDataset` class from `anndata._core.sparse_dataset` that:

* Acts equivalently on a type level. E.g. `ininstance(x, SparseDataset)` should be equivalent to `isinstance(x, (CSCDataset, CSRDataset))`
* Throws a `FutureWarning` on instance checks that tells people to replace it's usage with `sparse_dataset(x)` or `isinstance(x, (CSCDataset, CSRDataset))`
* Should act equivalently on instantiation: `SparseDataset(x)` should be equivalent to `sparse_dataset(x)`

I think the above should be enough.

I think this would look like:

```python
from abc import ABC
import warnings

from anndata.experimental import CSRDataset, CSCDataset, sparse_dataset


_sparsedataset_depr_msg = """\
SparseDataset is deprecated and will be removed in the future. It has been replaced by the public classes CSRDataset and CSCDataset.

For instance checks, use `isinstance(X, (anndata.experimental.CSRDataset, anndata.experimental.CSCDataset))` instead.

For creation, use `anndata.experimental.sparse_dataset(X)` instead.
"""

class SparseDataset(ABC):
    def __new__(cls, group):
        warnings.warn(FutureWarning(_sparsedataset_depr_msg), stacklevel=2)
        return sparse_dataset(group)

    @classmethod
    def __subclasshook__(cls, C):
        warnings.warn(FutureWarning(_sparsedataset_depr_msg), stacklevel=3)
        return issubclass(C, (CSRDataset, CSCDataset))
```

cc: @ilan-gold @martinkim0 @flying-sheep

**Comment by martinkim0** [comment]
This would be great! I've patched this in https://github.com/scverse/scvi-tools/pull/2271

**Comment by bykovam** [comment]
> This would be great! I've patched this in [scverse/scvi-tools#2271](https://github.com/scverse/scvi-tools/pull/2271)

I'm seeing issues attempting to importing scvi-tools and anndata together. Running the "import scvi" command in Jupyter Notebook leads to an import error: ImportError: cannot import name 'SparseDataset' from 'anndata._core.sparse_dataset'

**Comment by martinkim0** [comment]
Hi @bykovam, the patch has not been released yet so the import will still be broken with the newest version of scvi-tools (1.0.3). I believe that AnnData 0.10.2 fixes this though.

**Comment by bykovam** [comment]
I'll install the latest version and see if it helps
