### ISSUE TITLE
Minimum dependencies test job

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1203]
### Please describe your wishes and possible alternatives to achieve the desired result.

We should be testing against minimum versions of our dependencies. This is motivated by several recent issues related to pandas versions.

I propose we add a test job that grabs the minimum bounds of our dependencies and tests against it.

* This should test against our minimum python version
* This should run on main and release branches
* This should include optional dependencies
* We should figure out what the minimum version required is for our dependencies. I would propose:
  * Recently added and optional dependencies can have high lower bounds
  * Core dependencies should try and follow [SPEC 0](https://scientific-python.org/specs/spec-0000/)
* Keeping the job up to date with the `pyproject.toml` must be automated.

Unfortunately, it doesn't look like there's a great way to automate the job:

* https://github.com/pypa/pip/issues/8085

We can probably just write a script to parse this from our `pyproject.toml`.

cc: @flying-sheep

**Comment by flying-sheep** [comment]
> We can probably just write a script to parse this from our pyproject.toml.

Very easily. If we run that job in Python 3.11, we don’t even have to add a test dependency, we can just use the built-in `tomllib` module to parse `pyproject.toml` and grab the list of version specifier strings with it.

Then parse it using [packaging.specifiers.SpecifierSet](https://packaging.pypa.io/en/latest/specifiers.html) and transform it into a list of `==` specs.

Then begins the “fun” of finding out what the real minimum versions are that we support.

**Comment by ivirshup** [comment]
This gets more complicated for cupy since:

* You gotta specify the version of CUDA if you install cupy from pip
* CUDA is installed for the system image, not via pip

So we may need to upgrade out GPU testing system to let us use other versions of CUDA, so that we can support older cupy to test against them.

**Comment by ivirshup** [comment]
Another potential solution is to use https://pypi.org/project/pypi-timemachine/, which would help with transitive dependencies. However, I think this raises some new questions like: "what date do we set it to" and "what if a particular dependency should be from a newer date".

**Comment by flying-sheep** [comment]
Yeah, I feel like a PyPI time machine is more for “I can’t figure out how to get a working environment for this old thing anymore”, not our use case.
