### ISSUE TITLE
AnnData 0.10.2/0.10.3 with Pandas 2.0.x tries to use `Categorical.map(na_action=...)` introduced in Pandas 2.1

### ISSUE THREAD

**Issue by dsm-72** [scverse/anndata#1225]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

I am also noticing something strange with anndata 0.10.3 vs anndata 0.10.1 and pandas 2.0.3

Code:

```python
ad.concat([*adatas], ...)

```

Traceback:

```
File ~/.conda/envs/myenv/lib/python3.11/site-packages/anndata/compat/__init__.py:400, in _map_cat_to_str(cat)
    397 def _map_cat_to_str(cat: pd.Categorical) -> pd.Categorical:
    398     if _parse_version(pd.__version__) >= _parse_version("2.0"):
    399         # Argument added in pandas 2.0
--> 400         return cat.map(str, na_action="ignore")
    401     else:
    402         return cat.map(str)

TypeError: Categorical.map() got an unexpected keyword argument 'na_action'
```

### Versions

```python
anndata >=0.10.2, <=0.10.3
```

**Comment by flying-sheep** [comment]
Seems like the version check is wrong, it was [added in pandas 2.1.0](https://pandas.pydata.org/docs/whatsnew/v2.1.0.html#other-enhancements), not in 2.0:

> `Categorical.map()` and [`CategoricalIndex.map()`](https://pandas.pydata.org/docs/reference/api/pandas.CategoricalIndex.map.html#pandas.CategoricalIndex.map) now have a `na_action` parameter. `Categorical.map()` implicitly had a default value of `"ignore"` for `na_action`. This has formally been deprecated and will be changed to `None` in the future. Also notice that [`Series.map()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html#pandas.Series.map) has default `na_action=None` and calls to series with categorical data will now use `na_action=None` unless explicitly set otherwise (pandas-dev/pandas#44279)

**Comment by grst** [comment]
This breaks CI for me (e.g. https://github.com/scverse/scirpy/pull/467). 
Can someone make a bugfix release please?

**Comment by flying-sheep** [comment]
Sure!
