### ISSUE TITLE
Sparse matrices written with 32bit indptr

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#1261]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [X] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

Sparse matrices are currently being written with 32bit indptrs. They should be written with 64bit indptr so that we can append to them freely.

In particular, this is causing problems when writing large dask arrays where each chunk has an indptr that can fit in 32bit indices.

I could have sworn we were always writing matrices with 64 bit indptr, but need to check that. I'm not sure when this would have changed. I think it would have been quite easy to miss since it's difficult to test without using more memory/ disk space than our CI typically allows.

### Versions

```python
In 0.10.4 and main branch
```

**Comment by ivirshup** [comment]
Thinking about less aggressive ways of fixing this rather that always writing 64 bit:

* `SparseDataset.append` can check whether we're going to overflow and either error or rewrite

**Comment by ivirshup** [comment]
Sorry @flying-sheep , missed your comment. I think it's performance in the sense of "high performance computing" in that in only comes up with very large dataset size. But also things will be faster if we're 32bit whenever we can.

---------

As a workaround when using dask with sparse chunks right now, you can run:

```python
    def with_int64_indptr(x):
        x.indptr = x.indptr.astype(np.int64)
        return x
    elem = elem.map_blocks(with_int64_indptr, dtype=elem.dtype)
```

To write with 64bit indptr.

**Comment by mumichae** [comment]
This workaround gives me the same `ValueError: Output dtype not compatible with inputs` error as in https://github.com/scverse/anndata/issues/1349  when I try to persist.

```
def with_int64_indptr(x):
    x.indptr = x.indptr.astype(np.int64)
    return x
elem = elem.map_blocks(with_int64_indptr, dtype=elem.dtype).persist()
```

**Comment by ivirshup** [comment]
@mumichae, I suspect that may be more related to https://github.com/scverse/anndata/issues/1349

**Comment by ivirshup** [comment]
We've sorta solved this for dask arrays. We also now throw an error if you try to append too much to one of these.
