### ISSUE TITLE
Should the anndata constructor convert datatypes by default?

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#129]
I was just converting some data from R to python and was trying to debug why I was getting a different amount of total counts. In particular why `sum(adata.X.data)` was off by over 1000 from `np.sum(adata.X.data)`. Ended up turning the difference was floating point error, and `sum` was more accurate (also gave a more similar answer to R).

I'd generally expect calculations like "how many counts did this cell/ dataset have" to be precise.

Following the decision that `float32` isn't intended to be an automatic conversion anymore for most functions in scanpy, could we change the by-default conversion to `float32` in the `AnnData` constructor? I'm thinking we can keep the argument, just have the default be `None`.

**Comment by falexwolf** [comment]
Very happy to do that. You're right! Am just fixing it.

**Comment by falexwolf** [comment]
OK, done: https://github.com/theislab/anndata/commit/b92e7c38d10f3df7e8ac263a3547f210f0dee189

Can we target releasing 0.7? Anything against that @flying-sheep?

**Comment by flying-sheep** [comment]
Nope, there’s nothing urgent that needs to go in and no experimental changes since 0.6.19!

**Comment by falexwolf** [comment]
OK, this has wider implications than thought and breaks several of Scanpy's tests...

I reverted the commit (https://github.com/theislab/anndata/commit/002ac7f1d5c885824729dd8744445e0de205a762) and opened a PR.

This is now on https://github.com/theislab/anndata/pull/130 and listed here: https://github.com/theislab/scanpy/issues/453.

**Comment by ivirshup** [comment]
Awesome, thanks!

For future reference, would it be useful if travis also ran the scanpy tests for anndata builds?

**Comment by falexwolf** [comment]
Yes, that would indeed be useful... ;)

Should be easy to do. Probably Phil has the most elegant solution here...

**Comment by flying-sheep** [comment]
Well, we just have to add a line like `pytest /home/travis/virtualenv/python*/lib/python*/site-packages/scanpy`.

**Comment by flying-sheep** [comment]
fixed in #854
