### ISSUE TITLE
Check indexing arg types

### ISSUE THREAD

**Issue by ilan-gold** [scverse/anndata#1293]
### Please describe your wishes and possible alternatives to achieve the desired result.

Working on https://github.com/scverse/anndata/issues/1224, we discovered that `np.where` is called internally by `scipy` on boolean masks, but [there are places in our code](https://github.com/scverse/anndata/pull/1233#issuecomment-1859723394) where we also call it, likely unnecessarily.  It would be good to review these places to see if they are still necessary and then see if there is an effect on performance.

**Comment by ivirshup** [comment]
My main concern here is whether doing `adata[adata.obs[...] == ...].X` will hit the optimized path for indexing if `X` is backed (since we only optimized for mask indexing, and not positional)

**Comment by ivirshup** [comment]
It does not, which kind of defeats the optimization. This now needs doing.

**Comment by flying-sheep** [comment]
slight aside: `np.where` is designed for `np.where(cond, vals_if_true, vals_if_false)`, using it as replacement for `np.flatnonzero` is awkward.

**Comment by flying-sheep** [comment]
@ilan-gold what’s missing here?

**Comment by ilan-gold** [comment]
Closing this as it is no longer needed.  I've gone through the remaining instances and haven't found any that affect the performance optimizations.
