### ISSUE TITLE
reading directly from S3

### ISSUE THREAD

**Issue by djarecka** [scverse/anndata#1323]
### Please describe your wishes and possible alternatives to achieve the desired result.

I would like to read anndata files directly from S3 without need to download them. Some existing anndata file are pretty big, and we can't ask everyone to download the content first.

This is related to the discussion in #634

Possible solution:
Using [remfile](https://github.com/magland/remfile/tree/main) library that provides a file-like object for reading a remote file over HTTP, optimized for use with h5py. See a draft PR #1322

**Comment by flying-sheep** [comment]
OK so https://github.com/scverse/anndata/issues/634 is an existing issue for this. Sorry for the confusion.

I’m going to close this issue, we’ll figure out the best path in #634 and go from there!
