### ISSUE TITLE
Boolean subsetting selects incorrect index labels causing duplicate rows

### ISSUE THREAD

**Issue by aeisenbarth** [scverse/anndata#1331]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

When using a boolean index to select observations, the subset dataframe contains almost only identical values. The resulting obs names contain duplicates, as if False=obs_names[0] and True=obs_names[1]. This only occurs if the index is a plain list of booleans, not a Numpy array.

Code:

```python
import anndata
import pandas as pd
import numpy as np

table = anndata.AnnData(obs=pd.DataFrame({"col1": [0.0, 1.0, 2.0, np.nan]}, index=["1", "2", "3", "4"]))
mask = [True, False, True, True]
subset_table = table[mask, :]
# >>> print(subset_table.obs)
#    col1
# 2   1.0
# 1   0.0
# 2   1.0
# 2   1.0
expected_obs = pd.DataFrame({"col1": [0.0, 2.0, np.nan]}, index=["1", "3", "4"])
pd.testing.assert_frame_equal(subset_table.obs, expected_obs)
```

However, `table[np.array(mask), :]` works corrrectly.

This issue only occurs with anndata==0.10.4, not with anndata==0.10.3 or earlier.

### Versions

<details>

```python
-----
anndata             0.10.4
numpy               1.23.5
pandas              1.5.3
session_info        1.0.0
-----
asciitree           NA
cloudpickle         2.2.1
colorama            0.4.6
cython_runtime      NA
dask                2023.3.1
dateutil            2.8.2
dill                0.3.6
entrypoints         0.4
exceptiongroup      1.0.4
fasteners           0.18
google              NA
h5py                3.9.0
jinja2              3.1.2
llvmlite            0.40.1
markupsafe          2.1.3
mpmath              1.3.0
msgpack             1.0.5
natsort             8.4.0
numba               0.57.1
numcodecs           0.11.0
numexpr             2.8.5
nvfuser             NA
packaging           23.1
psutil              5.9.0
pyarrow             13.0.0
pytz                2023.3
scipy               1.9.1
setuptools_scm      NA
six                 1.16.0
sparse              0.14.0
sphinxcontrib       NA
sympy               1.12
tblib               2.0.0
tlz                 0.12.0
toolz               0.12.0
torch               2.0.1+cu117
tqdm                4.66.1
typing_extensions   NA
wheezy              NA
yaml                6.0.1
zarr                2.16.1
zoneinfo            NA
-----
Python 3.9.17 (main, Jul  5 2023, 21:05:34) [GCC 11.2.0]
Linux-5.15.0-91-generic-x86_64-with-glibc2.35
-----
Session information updated at 2024-01-25 11:23
```

</details>

**Comment by aeisenbarth** [comment]
I noticed this when using [`spatialdata_plot.pp.get_elements()`](https://github.com/scverse/spatialdata-plot/blob/595ea44e2a7414e23d9967ea180d54f4af467b2d/src/spatialdata_plot/pp/basic.py#L251) (@LucaMarconato not an issue in the new [`subset()`](https://github.com/scverse/spatialdata/blob/c1027a56b954074d7dcf64337dc3a9773dd43d95/src/spatialdata/_core/query/relational_query.py#L124)).

**Comment by ivirshup** [comment]
Thanks for the report!

This was introduced in the last anndata release and only applies when a list of booleans is passed as an index. If it's a boolean array (e.g. `adata[adata.obs["column"] == "value"]`) then it still works. Seems to have been introduced by: #1243
