### ISSUE TITLE
`FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'` on CI

### ISSUE THREAD

**Issue by ilan-gold** [scverse/anndata#1433]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [X] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

See: https://dev.azure.com/scverse/anndata/_build/results?buildId=6102&view=logs&j=3fc1c72d-f68c-5e9d-d0cf-b19bf30ca145&t=01d1bbda-b509-5b15-e986-0308bd93e634&l=53
 from https://github.com/scverse/anndata/pull/1432
### Versions

```python
N/A
```

**Comment by ivirshup** [comment]
This one turned out to be installing a too-old version of llvm-lite, right?

**Comment by ilan-gold** [comment]
Yes we can close.  Fixed by #1435 although I am still not clear what happened.  Embrace the mystery, I guess
