### ISSUE TITLE
2D indexing (no “:”) in `sparse_dataset` is not lazy

### ISSUE THREAD

**Issue by flying-sheep** [scverse/anndata#1520]
https://github.com/scverse/anndata/blob/b78a8056008eac5732379f9024c3b46d2b7d5d3f/src/anndata/_core/sparse_dataset.py#L179

calls `self._get_submatrix(...)`, which calls [`scipy.sparse.sparsetools.get_csr_submatrix(...)`](https://github.com/scipy/scipy/blob/e1fecdfb0eb4f1bc01345b0a39930ab1cc94e1da/scipy/sparse/sparsetools/csr.h#L1181).

And that one is implemented in C++, so it converts all of `self.indices` and `self.data` into arrays on each slice access.

This eliminates the whole purpose of `sparse_dataset` …

**Comment by Koncopd** [comment]
So the whole matrix gets loaded on slicing, not only the slice itself?
Is this a recent problem?

**Comment by flying-sheep** [comment]
I don’t know. I think it’s not recent, since `sparsetols/csr.h` is 17 years old. I didn’t look for the commit that makes C++ functions call `__array__` on their array arguments, but I don’t think it’s likely that that one is new.

**Comment by Koncopd** [comment]
Hm, i remember i had some horrible performance when trying to stream small slices of `sparse_dataset` for the cloud. This probably explains that.

**Comment by flying-sheep** [comment]
Testing this isn’t straightforward, but possible, so I think if we can find a fix, I can make the tests catch any possible regression.

The test fix would be something like monkeypatching `zarr.Array.__array__` so it throws an AssertionError when `len(return_arr) == len(sparse_dataset.data)`

But we still need an actual fix.

**Comment by ilan-gold** [comment]
1. This is only one case @flying-sheep.  The entire class is not not-lazy.  In fact much of it is lazy, unless the report is about more than just one line.
2.  This has likely has a solution by fetching along the major axis first via a slice and then slicing the minor from that slice.  This would be lazy from what I can tell off hand.
3.  `indptr` is a very manageable size even at the largest end of the spectrum, so loading it into memory is not an issue.  It is the size of the major axis.  Even at 100,000,000s of elements, that's still on the order of single digit gigabytes.

**Comment by flying-sheep** [comment]
Right, it doesn’t happen under all circumstances, only when you slice both dimensions at once, so that workaround works!

The `indptr` thing made sense, I thought as much since that `@property` is clearly there intentionally!

**Comment by flying-sheep** [comment]
This is hard to do right. I think an effective way for common use cases is really just to slice along the major axis first to get a in-memory sparse matrix with the full minor axis length, and then slice that in-memory.

A more space-efficient alternative is to re-implement `get_cs[rc]_submatrix` in a backing-aware way, but that would mean to write compiled code that uses the HDF5 or Zarr APIs (or suffering from the extreme slowness of assembling a matrix row-by-row in Python)
