### ISSUE TITLE
ad.read_zarr doesn't return `.uns` nor `.obsm`

### ISSUE THREAD

**Issue by BioinfoTongLI** [scverse/anndata#1572]
### Please describe your wishes and possible alternatives to achieve the desired result.

Hello there, thanks for the great tool!

I've been using read_zarr to accesss anndata.zarr stored on s3 bucket.
And I've noticed that both `.uns` and `.obsm` are missing. But if I do read_zarr against the exact same zarr locally, I do have them loaded.
I believe [this](https://github.com/scverse/anndata/blob/main/src/anndata/compat/__init__.py#L301) is part of the reason why `uns` are not there?

But I don't know why `obsm` is missing as well. Or do I missed a doc somewhere?
Many thanks!

Best,

**Comment by flying-sheep** [comment]
as Ilan said, duplicate

**Comment by BioinfoTongLI** [comment]
Many thanks both! I will follow the instruction above for uns and obsm! and sorry for the duplicates! Didn't seem that thread!
