### ISSUE TITLE
read_csv irmproperly parses first column if wrapped in quotes and has comma in string

### ISSUE THREAD

**Issue by adkinsrs** [scverse/anndata#1573]
### Please make sure these conditions are met

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

Issue originated in https://github.com/IGS/gEAR/issues/847

We have a web analysis portal that receives single-cell data from researchers (stored as h5ad files), and one of our analysis tools is to offer projections, where the output is a "sample" column and 1 or more weight metrics with values. Some of these sample names get kind of descriptive, and we wrap them in quotes to ensure the sample is not mis-parsed.  Below is an example where we use `scanpy.read_csv` (which goes to `anndata.read_csv`) and it seems that the function is not respecting the quotes, and is parsing the first column anyways (note the comma after Astrocyte)

```text
,FC
"GSE35338_Biomat_20___BioAssayId=165640Name=Astrocyte,1dayaftersham,biologicalrep4",253.03062
"GSE35338_Biomat_30___BioAssayId=165642Name=Astrocyte,1dayaftersham,biologicalrep3",286.72318
"GSE35338_Biomat_26___BioAssayId=165644Name=Astrocyte,1dayaftersham,biologicalrep2",249.17116
"GSE35338_Biomat_28___BioAssayId=165646Name=Astrocyte,1dayaftersham,biologicalrep1",246.8108
"GSE35338_Biomat_2___BioAssayId=165631Name=Astrocyte,1dayaftersaline,biologicalrep4",229.42839
"GSE35338_Biomat_19___BioAssayId=165632Name=Astrocyte,1dayaftersaline,biologicalrep3",270.16727
"GSE35338_Biomat_16___BioAssayId=165634Name=Astrocyte,1dayaftersaline,biologicalrep1",235.23557
"GSE35338_Biomat_18___BioAssayId=165633Name=Astrocyte,1dayaftersaline,biologicalrep2",231.75357
"GSE35338_Biomat_21___BioAssayId=165641Name=Astrocyte,1dayafterMCAO,biologicalrep5",389.83023
```

Code:

This is what I executed in the REPL. The file's name for this example will be "test.csv"

```python
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import anndata
>>> adata = anndata.read_csv("./test.csv")
```

Traceback:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/Python-3.10.4/lib/python3.10/site-packages/anndata/_io/read.py", line 57, in read_csv
    return read_text(filename, delimiter, first_column_names, dtype)
  File "/opt/Python-3.10.4/lib/python3.10/site-packages/anndata/_io/read.py", line 360, in read_text
    return _read_text(f, delimiter, first_column_names, dtype)
  File "/opt/Python-3.10.4/lib/python3.10/site-packages/anndata/_io/read.py", line 423, in _read_text
    data.append(np.array(line_list[1:], dtype=dtype))
ValueError: could not convert string to float: '1dayaftersham'
```

### Versions

```python
-----
anndata             0.10.6
session_info        1.0.0
-----
cloudpickle         2.2.0
cython_runtime      NA
dask                2022.9.2
dateutil            2.8.2
exceptiongroup      1.2.2
fsspec              2022.8.2
h5py                3.10.0
jinja2              3.1.2
llvmlite            0.41.1
markupsafe          2.1.1
natsort             8.2.0
numba               0.58.1
numexpr             2.8.4
numpy               1.26.0
packaging           24.1
pandas              2.2.1
psutil              5.9.2
pytz                2022.4
scipy               1.11.4
six                 1.16.0
sparse              0.13.0
tlz                 0.12.0
toolz               0.12.0
typing_extensions   NA
yaml                6.0
zoneinfo            NA
-----
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Linux-6.5.0-1025-gcp-x86_64-with-glibc2.35
-----
Session information updated at 2024-08-04 02:00
```

**Comment by flying-sheep** [comment]
CSV is not a standardized format, so that’s what happens when you use it.

I generally recommend to everyone to avoid CSV like the plague, since problems like this *will* happen more subtly at some point, you’ll miss it, and it’ll destroy your results.

Don’t use CSV, and you won’t have problems like this.

PS: this applies to all “separator delimited text” formats like CSV, TSV,  …

**Comment by adkinsrs** [comment]
The what is the point of having a `read_csv` function if you are discouraging people from using it, due to the non-standardization issues of the format.  In my opinion, if it is discouraged at least have a note or warning in the function's documentation to avoid using CSV or similar delimited formats so others won't blindly use it and have other related issues.
