### ISSUE TITLE
(dev): Automation for cherry-picking release notes to `main` from `0.X.X` branch

### ISSUE THREAD

**Issue by ilan-gold** [scverse/anndata#1620]
### Please describe your wishes and possible alternatives to achieve the desired result.

Right now, if we make a release notes fix on a minor branch e.g., `0.10.x` branch, we need to manually cherry pick it to `main`, although this should be doable with an automated PR from the release process.

**Comment by flying-sheep** [comment]
The meeseeks-bot can be controlled by labels:

> You can also set a Label or a Milestone which description [c]ontains `on-merge: backport to [BRANCHNAME]`

so adding a label with that description to the release PR would do the trick!

**Comment by ilan-gold** [comment]
Ah great! cherry picking is no fun!
