### ISSUE TITLE
0.11 API

### ISSUE THREAD

**Issue by flying-sheep** [scverse/anndata#1634]
# new top-level

- [x] #1644
- [x] #1641

# .experimental
 
- [x] #1642
- [x] `experimental.read_elem_as_dask` → `experimental.read_elem_lazy`? Not yet: https://github.com/scverse/anndata/issues/1634#issuecomment-2325894399
- [x] #1643

# new modules

- [x] #1645

**Comment by ilan-gold** [comment]
> idea: move read_zarr in together with .h5ad as “native file format”

So one `read` function?  We then need a dependency on `zarr` then probably

> experimental.sparse_dataset needs to come to the same place as CS{RC}Dataset or be removed.

Exported then, it is fairly stable.

> Maybe .arrays and .types submodule?

Hmmm, I like `types` but `arrays` is not great if we're also going to export views, maybe some xarray dataset stuff etc.  Better name, I'm all for it.  But even there, I don't want to actually export anything beyond what's needed for type checking and the bare minimum needed for basic usage (only `CS{R,C}dataset` ATM)

> [InMemoryElem](https://anndata.readthedocs.io/en/latest/generated/anndata.InMemoryElem.html#anndata.InMemoryElem) needs a docstring for a nicer list entry on the API page (like RWAble)

Yes ok!

**Comment by flying-sheep** [comment]
> So one read function?

no, just move it up in the docs:

![grafik](https://github.com/user-attachments/assets/85c606a6-13ab-4237-9458-98638b28c49b)

> Exported then, it is fairly stable.

It’s 3 lines, I don’t know if we need to have it at all. People could trivially re-implement it.

But I’m also OK with exporting it.

> Better name, I'm all for it. 

ah yes, the famous second-hardest thing in computer science: naming things. We have the following categories of types that we export or might want to export:

- Containers (owning data): AnnData, AlignedMapping
- Views (referencing data in a container): AnnData(!), CupyArrayView, CSRArrayView, … (all(?) identical or inheriting from the parent array)
- Datasets (referencing data on disk): CSRDataset, …

Am I missing something? E.g. we have actual in-memory array containers?

`np.ndarray` and `AnnData` don’t have dedicated view classes, so maybe we should just export a protocol named `View` with the [np.ndarray.base](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.base.html) API? If there is just one `View` protocol / abstract base class for all array types we support, it could go wherever.

**Comment by ilan-gold** [comment]
> It’s 3 lines, I don’t know if we need to have it at all. People could trivially re-implement it.

This is from Isaac, I didn't really understand at the time the advantage of this, although I would guess it was to avoid exposing the underlying class.   Not a great reason though TBH since we expose it anyway by virtue of it being on the `AnnData` object

> Am I missing something? E.g. we have actual in-memory array containers?

Not really from what I can tell

> np.ndarray and AnnData don’t have dedicated view classes

`ndarray` does? https://github.com/scverse/anndata/blob/0bc2b396b7c48bd37b51e70233e6ac92cbbbf35d/src/anndata/_core/views.py#L296-L298

I will tag you in a PR soon about the view business

**Comment by flying-sheep** [comment]
> Not a great reason though TBH since we expose it anyway by virtue of it being on the AnnData object

If we would only advertise a protocol/ABC instead, we could get around exporting them. So I’d say either we delete the function or we move it and export a protocol/ABC instead of the `CS{CR}Dataset` classes.

> `ndarray` does? 

What I‘m saying is that `numpy.ndarray` itself works like `AnnData` in that an attribute tells you if an instance is a view or not, and `numpy` doesn’t define an array view class.

**Comment by ilan-gold** [comment]
For views, why not suggesting in the docs checking as follows for views:

```python
isinstance(adata_view.obsm['my_array'], ArrayClass) and adata_view.is_view
```

**Comment by flying-sheep** [comment]
Hm they are in `experimental` so I guess churn is to be expected. OK!

But `RWAble` and `InMemoryElement` are probably not great names:

- `RWAble` is “arrays that we can stick into AnnData.obsm/.varm and that we can read and write”
- `InMemoryElement` is “all things we can read and write”

so maybe better names would be

- `RWAble` → `RWAbleElement` or `SerializablePart` or so
- `InMemoryElement` → `RWAble` or `Serializable`

**Comment by ilan-gold** [comment]
> But RWAble and InMemoryElement are going to be exporten, and given their close relationship, they are probably not great names:

Totally agree, noticed that writing the docstrings.  Maybe `RWAble` -> `AxisArrayStoreable` since it is used concretely in our code for `read_mapping` and then `InMemoryElem` -> `RWAble`?

**Comment by flying-sheep** [comment]
Sounds good to me! If you want to do this, please rename them in two subsequent commits so we can be sure all instances of `RWAble` have been renamed
