### ISSUE TITLE
Unexpected Behavior: AnnData Allows Indexing with Float Arrays Without Error

### ISSUE THREAD

**Issue by yubin-ai** [scverse/anndata#1735]
### Please make sure these conditions are met

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of anndata.
- [ ] (optional) I have confirmed this bug exists on the master branch of anndata.

### Report

I encountered unexpected behavior when indexing an AnnData object using a list of float values. While indexing with a single float correctly raises an IndexError, indexing with a list or array of floats does not raise an error and proceeds as if the floats were valid indices. This seems inconsistent and could lead to unintended results.

Code:

```python
import anndata
import numpy as np

# Create a sample AnnData object
adata = anndata.AnnData(np.random.rand(100, 10))

# Indexing with a single float value raises an error (as expected)
try:
    adata[43.4, :].obs
except IndexError as e:
    print(f"Single float index error (expected): {e}")

# Indexing with a list of floats does not raise an error (unexpected behavior)
float_indices = [42.85256014, 62.04391223, 26.08972756, 54.38563822, 90.45806554, 78.73412668]
try:
    result = adata[float_indices, :].obs
    print("Indexing with float list succeeded (unexpected):")
    print(result)
except IndexError as e:
    print(f"Float list index error (expected): {e}")
```

Traceback:

```pytb
Single float index error (expected): Unknown indexer 43.4 of type <class 'float'>
Indexing with float list succeeded (unexpected):
Empty DataFrameView
Columns: []
Index: [42, 62, 26, 54, 90, 78]
```

### Versions

-----
anndata             0.10.9
numpy               1.26.4
pandas              2.2.3
session_info        1.0.0
torch               2.5.0+cu124
tqdm                4.66.5
...
Python 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
Linux-5.10.226-214.880.amzn2.x86_64-x86_64-with-glibc2.36

**Comment by ilan-gold** [comment]
Hmm, @yubin-ai I am not sure this is unexpected, but perhaps strange.  For example:

```python
import anndata as ad
import pandas as pd

adata = ad.AnnData(obs=pd.DataFrame({ 'a': ['c', 'b']}, index=[1.2, 1.3]))
adata[[1.2]]
```
but
```
adata[1.2]
```
would error.  In general, I think floating numbers as an index is probably fine, but this raises a question of ambiguity with integers as well.  If someone has an integer index, how should we interpret those integers?  pandas has mechanisms for disambiguating the purpose of an indexing object, whether its label-based (as above) or its positional.

@flying-sheep thoughts here?

**Comment by yubin-ai** [comment]
@ilan-gold Indeed, it’s strange. In your case, using floats as query seems logical that there are floats index. However, in my example, none of the indices are floats. It appears that adata, or perhaps just the underlying pandas DataFrame, rounds the float to an integer and then selects the rounded index, which is concerning since it returns entries that don’t actually exist/match. My title might have to be modified a bit to describe this more clearly.

In my case, the float input was due to an error on my end—a wrong variable was passed—and I didn’t catch it because of how smoothly it was handled. A quick assertion or error check to confirm the query index exists in adata.obs.index could help prevent issues like this.

**Comment by ilan-gold** [comment]
@yubin-ai I have just been informed we only accept string indices, so my example doesn't really work.  So I really think we should just error out then.  Thanks for the issue

**Comment by yubin-ai** [comment]
@ilan-gold an error out sounds great. Thanks a lot for working on it!
