### ISSUE TITLE
Slowdown when initializing from a large sparse matrix

### ISSUE THREAD

**Issue by huidongchen** [scverse/anndata#199]
Hi 

Thanks for the fantastic package!

I'm trying to initiate an Anndata object using the backing file. but i got the errors `'The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().'` . The error can be reproduced by

```py
import anndata as ad
from scipy.sparse import csr_matrix, csc_matrix

X_array = np.array(
    [[0, 1, 0],
     [0, 0, 2],
     [0, 0, 0],
     [3, 4, 0]])
# make this a sparse matrix
X = csr_matrix(X_array)
adata = ad.AnnData(X,filemode='r+',filename='test.h5ad')
```
Thank you for any help you can offer!

**Comment by ivirshup** [comment]
Thanks for the kind words!

The `AnnData` constructor assumes a dataset already exists if you pass the filename. I'm also not sure it works so well. We should probably document this better. I think what you want to do in this case would be something more like:

```python
mem_adata = ad.AnnData(X)
mem_adata.write("test.h5ad")
backed_adata = ad.read("test.h5ad", backed="r+")
# Or
adata = ad.AnnData(X)
adata.filename = "test.h5ad"
```

**Comment by ivirshup** [comment]
In this case I think it might currently be easiest to work with `h5py` or a memory mapped array directly. Specifically how will depend on your use case. Can you tell me a bit about how you plan on building this array? Will you be getting all of the data for each sample at once, or in random order?

**Comment by huidongchen** [comment]
I'm planning to get all of the data at once. Essentially I wanted to initiate anndata with a huge empty sparse matrix consisting of all the regions and cells. Then I will read in single-cell file one by one and update it by specifying the indices and columns.

I actually also tried h5py before and tried to save it as `.h5` file. But later I ran into a different error while reading it into anndata. The error can be reproduced with the following steps:

```
n_regions = 10000
n_cells = 100
X = csr_matrix((n_regions, n_cells), dtype=np.float32)
f = h5py.File('./test.h5')
f.create_dataset('X', data=X)
adata = ad.read_hdf('./test.h5',key='X')
```
The error is 'AttributeError: 'Dataset' object has no attribute 'copy''

Thanks again for your help!

**Comment by ivirshup** [comment]
So h5py doesn't really have a sparse matrix format, so I think that's causing your error. We've implemented our own here, which you could write.

We represent a csr sparse matrix as a group with the datasets. Here's an example of what that would look like:

```python
import anndata
import h5py
from scipy import sparse
import numpy as np

adata = anndata.AnnData(sparse.random(10, 10, format="csr"))
adata.write("test.h5ad")

!h5ls -r test.h5ad
# /                        Group
# /X                       Group
# /X/data                  Dataset {1/Inf}
# /X/indices               Dataset {1/Inf}
# /X/indptr                Dataset {11/Inf}
# /obs                     Group
# /obs/_index              Dataset {10}
# /var                     Group
# /var/_index              Dataset {10}
```

The underlying datasets correspond directly to the csr matrices underlying arrays. There are also some attributes which let us know what kind of sparse format it's in, and what the matrices shape is:

```python
with h5py.File("test.h5ad", "r") as f:
    assert np.all(f["X/data"][:] == adata.X.data)
    assert np.all(f["X/indices"][:] == adata.X.indices)
    assert np.all(f["X/indptr"][:] == adata.X.indptr)

    print(dict(f["X"].attrs))
# {'h5sparse_format': 'csr', 'h5sparse_shape': array([10, 10])}
```

I think creating an hdf5 group this way might work, though it's performance later will be very dependent on what you're planning on doing later.

@Koncopd, do you have any thoughts on this?

**Comment by Koncopd** [comment]
@ivirshup 
There is [append functionality](https://github.com/theislab/anndata/blob/1b28414392e9a938a1f697e93002c3dbabe10c41/anndata/h5py/h5sparse.py#L323), maybe it can help doing this.

But i'm not sure i understand the task.
@huidongchen , do you wand to convert your data file to h5ad without loading the whole data into memory?

**Comment by huidongchen** [comment]
Thanks a lot for the suggestions and advice. They are very helpful!

@koncopd, yes, exactly! I want to covert my huge sparse matrix into h5ad file without using the memory mode.

**Comment by Koncopd** [comment]
And where do you have your huge sparse matrix?

**Comment by huidongchen** [comment]
I initialized it using 

‘X = csr_matrix((n_regions, n_cells), dtype=np.float32)’ 

Here ‘n_region’ can be a huge number. So it’s still in memory. 

Then I would like to covert ‘X’ into anndata object and write it to a h5ad file

**Comment by ivirshup** [comment]
@huidongchen, I wouldn't recommend instantiating a `csr_matrix` then populating it. Scipy's indexing code is very slow for this, even in cases it could be fast. I think you're best off either writing the matrix as an hdf5 dataset/ group directly through h5py. 

If you can give us some details on how your data is currently stored and what you plan on doing with it downstream we might be able to give some guidance on how to do this.

**Comment by huidongchen** [comment]
Hi , sorry about the delay.

We tried your csr solution with this matrix however this seems to always get expa

> So h5py doesn't really have a sparse matrix format, so I think that's causing your error. We've implemented our own here, which you could write.
> 
> We represent a csr sparse matrix as a group with the datasets. Here's an example of what that would look like:
> 
> ```python
> import anndata
> import h5py
> from scipy import sparse
> import numpy as np
> 
> adata = anndata.AnnData(sparse.random(10, 10, format="csr"))
> adata.write("test.h5ad")
> 
> !h5ls -r test.h5ad
> # /                        Group
> # /X                       Group
> # /X/data                  Dataset {1/Inf}
> # /X/indices               Dataset {1/Inf}
> # /X/indptr                Dataset {11/Inf}
> # /obs                     Group
> # /obs/_index              Dataset {10}
> # /var                     Group
> # /var/_index              Dataset {10}
> ```
> 
> The underlying datasets correspond directly to the csr matrices underlying arrays. There are also some attributes which let us know what kind of sparse format it's in, and what the matrices shape is:
> 
> ```python
> with h5py.File("test.h5ad", "r") as f:
>     assert np.all(f["X/data"][:] == adata.X.data)
>     assert np.all(f["X/indices"][:] == adata.X.indices)
>     assert np.all(f["X/indptr"][:] == adata.X.indptr)
> 
>     print(dict(f["X"].attrs))
> # {'h5sparse_format': 'csr', 'h5sparse_shape': array([10, 10])}
> ```
> 
> I think creating an hdf5 group this way might work, though it's performance later will be very dependent on what you're planning on doing later.
> 
> @Koncopd, do you have any thoughts on this?

Sorry about the delay. I tried your csr solution. but unfortunately in our case it doesn't work.

```
n_regions = 243154492
n_cells = 100
X = csr_matrix((n_regions, n_cells), dtype=np.float32)
adata = ad.AnnData(X)
```
`X` is supposed to be an empty sparse matrix and can be generated within one second. but when converting the empty sparse matrix `X` to anndata object, the step `adata = ad.AnnData(X)` gets stuck and it will take ~5 hours. It's quite puzzling to me since it's just an empty sparse matrix. Is anndata internally trying to convert it to a full matrix?

**Comment by flying-sheep** [comment]
The culprit might be this:

https://github.com/scverse/anndata/blob/642e5213fe50727c72cdf8e8f6df4049615d81b5/anndata/_core/anndata.py#L112

**Comment by ivirshup** [comment]
@flying-sheep 

* https://github.com/scverse/anndata/issues/777

Though I think I'm leaning towards non-numeric, but efficient, datatypes. Like a UUID as a fixed length byte-string. The previous big blocker to this seems to have been removed in pandas: 

* https://github.com/pandas-dev/pandas/issues/50121#issuecomment-1630560449

----

I think the original issue here was resolved. The subsequent discussion is tracked in #777 and likely has different performance characteristics today than it did when the issue was opened.

So I'm going to say we move the performance conversation there and mark this as closed.

**Comment by flying-sheep** [comment]
I’m interested in doing this, I wanted to do add UUID indices for quite some time!
