### ISSUE TITLE
Is logging "Transforming to str index." necessary?

### ISSUE THREAD

**Issue by dburkhardt** [scverse/anndata#311]
I do a lot of moving back and forth between DataFrames and AnnData objects, and the "Transforming to str index." warning can get annoying, especially if I'm running things in a loop:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/8322751/73389830-faea0f80-42a2-11ea-9ec1-06a64067d4bc.png">

In these cases, I'm creating a DataFrame using something like:

```python
data = np.random.normal(size=(1000,100))
data = pd.DataFrame(data)
... # code that expects data as a DataFrame
adata = sc.AnnData(data)
```

Does this need to be logged in a manner that is printed by default? Is there an easy way to disable this?

It looks like this is the offending line
https://github.com/theislab/anndata/blob/master/anndata/_core/anndata.py#L97

**Comment by flying-sheep** [comment]
It was introduced in 34f4eb63710628fbc15e7050e5efcac1d7806062

It triggers even if we have a RangeIndex, which shouldn’t trigger a warning.

I’m not sure if a Int64Index should trigger a warning, as it’s easy to get one by slicing a DataFrame with a RangeIndex.

**Comment by dburkhardt** [comment]
I also realized this bug raises an index error when you try to add `obs` annotations using a rangeindex:

```python
import scanpy as sc
import pandas as pd
import numpy as np
data = pd.DataFrame(np.random.normal(size=(100,2)))

adata = sc.AnnData(data)
adata.obsm['X'] = data
Transforming to str index.
Transforming to str index.
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-225-6822bcb62e23> in <module>
      5 
      6 adata = sc.AnnData(data)
----> 7 adata.obsm['X'] = data

~/.local/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py in __setitem__(self, key, value)
    148 
    149     def __setitem__(self, key: str, value: V):
--> 150         value = self._validate_value(value, key)
    151         self._data[key] = value
    152 

~/.local/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py in _validate_value(self, val, key)
    209         ):
    210             # Could probably also re-order index if it’s contained
--> 211             raise ValueError(
    212                 f"value.index does not match parent’s axis {self.axes[0]} names"
    213             )

ValueError: value.index does not match parent’s axis 0 names


```

**Comment by dburkhardt** [comment]
What's the reason for changing the index to str in the first place? Why not use the pd.Index object passed when you create the AnnData object?

**Comment by ivirshup** [comment]
AnnData objects use positional indexing when you supply numeric indices, but access by name when pass strings. If we allowed numeric indices that would statements like: `adata[0]` ambiguous. There's a little more detail on this in the [AnnData docstring notes](https://anndata.readthedocs.io/en/stable/anndata.AnnData.html#anndata.AnnData).

@flying-sheep, this is a logging warning, not an actual `warnings.Warning` right? It should probably be an actual warning so it's easier to catch and silence.

**Comment by flying-sheep** [comment]
Default behavior is that warnings display once per location where it’s raised: https://docs.python.org/3/library/warnings.html#the-warnings-filter

does that mean it gets shown once per location where it’s raised? that would be bad, as we want it to show every time a new AnnData object is created or has its index replaced.

**Comment by ivirshup** [comment]
Hmm. I'm not quite sure. I had thought location meant context/ stack-level, but I'm not sure if that's true. It'll definitely warn less than @dburkhardt is reporting:

```python
In [1]: import warnings                                                                                                                                                       

In [2]: def dangerous(): 
   ...:     warnings.warn("Woah there!", UserWarning) 
   ...:                                                                                                                                                                       

In [3]: def foo(): 
   ...:     for i in range(10): 
   ...:         dangerous() 
   ...:                                                                                                                                                                       

In [4]: foo()                                                                                                                                                                 
/usr/local/bin/ipython:2: UserWarning: Woah there!
  # -*- coding: utf-8 -*-

In [5]: foo()                                                                                                                                                                 
/usr/local/bin/ipython:2: UserWarning: Woah there!
  # -*- coding: utf-8 -*-
```

**Comment by flying-sheep** [comment]
This kinda looks ideal.

**Comment by dburkhardt** [comment]
Thanks for the help here all! I don't think this issue is closed though as the following code will still raise an error, when I don't think it should:

```python
import scanpy as sc
import pandas as pd
import numpy as np
data = pd.DataFrame(np.random.normal(size=(100,2)))

adata = sc.AnnData(data)
adata.obsm['X'] = data
```
Thanks for the clarification on positional vs names indices @ivirshup. I'm not sure that I like this paradigm of assuming that there need be `str` labels for each column. I understand that in the context of scRNA-seq one will often have cell barcodes, but it was my impression that `AnnData` is meant to be a more generalized data storage class (hence little mention of any specific technology in the docs). I usually think of it as `pd.DataFrame`-plus. 

I often have data with only numeric positional indices. It would be nice to have full support for this use-case correct? Shouldn't that code above work properly without raising an error? I think to do that you might need to let users who don't have non-numeric `obs_names` or `var_names`.

Another consideration here is what to do if I were to select a subset of that DataFrame before creating the AnnData object:

```python
adata = sc.AnnData(data.iloc[10:])
```

then the `obs` at position `0` will have index `10` in the DataFrame.

**Comment by flying-sheep** [comment]
It does? I thought we test if a DataFrame has a RangedIndex and don’t warn if it’s the case.

**Comment by ivirshup** [comment]
>  I'm not sure that I like this paradigm of assuming that there need be str labels for each column. 

I'm not the biggest fan of it either, but it's hard to move away from. Ideally there would be entirely separate methods for positional indexing and label based indexing (i.e. `loc` and `iloc`) but that isn't our API. When I first came across this, implementing that kind of API would have been very difficult, though could be easier now. For backwards compatibility we could probably never support integer label based access with `adata[idx]` syntax. There are also a lot of assumptions built into the ecosystem about this.

-------------------------------

```python
adata = sc.AnnData(data)
adata.obsm['X'] = data
```

@flying-sheep, if the passed object has a numeric index, we could try converting it to strings and check if that matches?

----------------------

@dburkhardt, there are some previous issues on this topic you might be interested in:

* https://github.com/theislab/anndata/issues/31
* https://github.com/theislab/anndata/issues/35

**Comment by flying-sheep** [comment]
> if the passed object has a numeric index, we could try converting it to strings and check if that matches?

that would work I guess. not really pretty, but I can’t think of how it would have unintentional side effects

**Comment by flying-sheep** [comment]
Let’s track this in #31. #954 fixed a bit more issues with strings.
