### ISSUE TITLE
adata.X = None raises “incompatible shape” error

### ISSUE THREAD

**Issue by flying-sheep** [scverse/anndata#330]
If we only want to support `del adata.X`, we need to change the pbmc tutorial.

**Comment by ivirshup** [comment]
Do you want to allow `del adata.X`?

**Comment by flying-sheep** [comment]
If `adata.X = None` should be legal, `del adata.X` should be too, right?

But yeah, right now there’s no way to do what the tutorial wants to …

**Comment by ivirshup** [comment]
I forget why this came up. I don't think we should allow `del adata.X` or `adata.X = None`.

Can we close this?

**Comment by LustigePerson** [comment]
I stumbled on the same thing while running your 3k PBMC tutorial. Are you planning to allow `del adata.X` or `adata.X = None`? Or is this functionality gone?

**Comment by ivirshup** [comment]
I would say the tutorial is out of date. I don't think we currently support having no value for `X`, since it's pretty central to how AnnData objects work.
