### ISSUE TITLE
Default join option in concatenate

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/anndata#390]
Now that outer join is super fast, I think we should consider making "outer" the default join option in concatenate. Main reason is that inner join removes genes, which is typically not preferred (e.g. subsetting genes do not subset genes in adata.raw bcs we try to preserve gene info as much as we can). Such genes can be easily removed later on, if the user wishes but after inner join it's not possible to bring them back. 

wdyt?

**Comment by falexwolf** [comment]
Hmmm. If it's just zero-padding, then I think that's fine for many pieces of code. If it's adding a ton of nans by default, much code will break.

So, I still think the conservative option is having the default to `inner` but I also see how it's more consistent with pandas to have `outer` as the default.

**Comment by falexwolf** [comment]
As we're just talking about defaults:
* `index_unique=None` would be my preferred default meanwhile
* for the `join` character for labeling `.var` entries from different batches, I'd think that `_` is better than the current `-` (also changed my opinion here, over the years)

What do you guys think?

**Comment by gokceneraslan** [comment]
Hey @falexwolf ,

> Hmmm. If it's just zero-padding, then I think that's fine for many pieces of code. If it's adding a ton of nans by default, much code will break.
> 
> So, I still think the conservative option is having the default to `inner` but I also see how it's more consistent with pandas to have `outer` as the default.

I think join='outer' and fill_value=0 (for both dense and sparse) are the most conservative default options because as I mentioned, inner removes genes and I think that's really bad and hard to recover. I have actually never used inner join in my life with AnnData :) In the old days, I was waiting for 4-5 hours sometimes, just to be able to use outer join :/

> * `index_unique=None` would be my preferred default meanwhile
> * for the `join` character for labeling `.var` entries from different batches, I'd think that `_` is better than the current `-` (also changed my opinion here, over the years)

I agree with these! Sounds good. 

Btw, is there a way to disable concatenation of `.var` entries? Sometimes, I have 10 objects with HVGs etc in `.var`, so when I concatenate them, I get a lot of columns in `.var` and I don't need them at all... Not a big deal, I can remove them before or after concatenation but just wanted to bring up in case other people also experirnce this.

**Comment by gokceneraslan** [comment]
More justification about outer join: Imagine you have subsetted immune cells and stromal cells from the same datasets as two anndata objects, did some things with them and then merged them back with default inner join. You might lose many important immune and stromal-related genes with important info. That might happen with samples with significant biological differences, so I really think intersection is a bad idea.

**Comment by gokceneraslan** [comment]
Actually, I think we can also add `intersection` and `union` as alias of `inner` and `outer`, that'd be arguably more understandable for many people.

**Comment by ivirshup** [comment]
Hey! Sorry for being late in catching up on this, but I have some thoughts (mostly coming from working on #378). First I'll go over the `join` default, then address some other default values you've brought up.

# Having `outer` be the default

My opposition to having `"outer"` be the default is the `fill_value` issue. Basically, I'm not super happy with our solution to `fill_value` and would like to be more hidden until there's a better one. I also like having the most performant and conservative option as the default. On the topic of `fill_values`:

* Pandas fills with `nan`, and doesn't let you choose something else
* xarray fills with `nan` by default
* We fill dense arrays with `nan`, sparse arrays with 0s, and `nan` for pandas

I think it makes sense to fill data that's like count matrices with `0`. It's often safe to assume that a gene that isn't present saw no counts. I don't think this holds for many other kinds of data. For example, if we were to pad the arrays of gene loadings for some embedding with 0s, that would be wrong. It would also be wrong to fill `total_counts` columns with 0s when really, the values weren't computed. For cases like these, defaulting to a missing value makes sense.

I think this one of a couple reasons we have the current behavior:

* Most often, data where it makes sense to fill with 0s is in sparse arrays, while data where a missing value would make sense is often in arrays or data frames.
* Putting nans in a sparse array is weird. First, we're breaking sparsity. Second, they can behave strangely:

```python
In [34]: a = sparse.random(5, 5, density=.2, format="csr")                                                                                                                                                                            

In [35]: b = sparse.random(5, 5, density=.2, format="csr")                                                                           

In [36]: a[0, 0] = np.nan                                                                                                            

In [37]: (a @ b).toarray()                                                                                                           
Out[37]: 
array([[0.        ,        nan,        nan, 0.        , 0.        ],
       [0.        , 0.76152071, 0.        , 0.        , 0.        ],
       [0.        , 0.3996578 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [38]: (a.toarray() @ b.toarray())                                                                                                 
Out[38]: 
array([[       nan,        nan,        nan,        nan,        nan],
       [0.        , 0.76152071, 0.        , 0.        , 0.        ],
       [0.        , 0.3996578 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])
```

To me, the correct fill values has a lot to do with the semantics of the data, and having one fill value to use for all elements of the `AnnData` objects is limiting. A solution to this would be allowing fill values to be specified on a more granular level. The default could be `nan` regardless of array type, and we could instead specify fill value by location. An API for this could be passing a "spec" to `fill_value`. Something like:

```python
ad.concat([a, b, c], fill_value={"X": 0, "layers/*": 0, "varp/*": np.nan})
```

But I think this would rely on #342.

# Other defaults

> index_unique=None would be my preferred default meanwhile

This is the current default for `ad.concat`

> Btw, is there a way to disable concatenation of .var entries? 

I've just left out the behavior of adding a column for each AnnData. Something like that could get added back as an option for `ad.concat`'s `merge` argument (which is how I've re-implemented `AnnData.concatenate`), but it wasn't something I ever really wanted.

**Comment by flying-sheep** [comment]
seems like this has been answered. let’s reopen if there’s outstanding questions/wishes
