### ISSUE TITLE
Option to select the variable with the highest median when making the index unique

### ISSUE THREAD

**Issue by fbrundu** [scverse/anndata#41]
Hi all,
when loading the data, in case of duplicates I usually choose the item with the highest median (e.g. the gene with the highest median signal). With a pandas DataFrame it can be done as easily as this:

```py
df = df.T
df['Median'] = df.median(axis=1)
df = df.sort_values(by=['Median'], ascending=False, na_position='last')
df = df.drop(columns=['Median'])
df = df.groupby(level=1).first()
df = df.T
```

considering genes in columns and samples in index. I find it more useful than:

https://github.com/scverse/anndata/blob/1c052902a98e04502a36ce46a12b22500a785f50/anndata/utils.py#L10

since you don't change the name of genes. I don't know however how to implement it using AnnData. Are you interested in integrating it in AnnData, maybe also with different options (e.g. average, etc.)?

Thanks,
Francesco

**Comment by flying-sheep** [comment]
No need to have special support, you can do it something like this:

```py
# raw data
data = scipy.sparse.csr_matrix(...)
obs = pd.DataFrame(..., index=...)  # index has duplicates

# order and deduplicate
order = obs.assign(Median=data.median(axis=1)).idxmax()
adata = AnnData(data[order], obs[order])
```
