### ISSUE TITLE
Unsetting backed does not restore data matrix to numpy ndarray

### ISSUE THREAD

**Issue by jlchang** [scverse/anndata#411]
If I create an anndata object, I'm able to run `adata.X.T` without issue.
However if I set `adata.filename = './back_test.h5ad'`,

running `adata.X.T`
now fails
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-c079a10fe4e2> in <module>
----> 1 adata.X.T

AttributeError: 'Dataset' object has no attribute 'T'
```
I tried to unset backed mode using `adata.filename = None`
Unfortunately, I'm still unable to transpose the matrix
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-c079a10fe4e2> in <module>
----> 1 adata.X.T

AttributeError: 'NoneType' object has no attribute 'T'
```
Is this the expected behavior?

Note that before backing, `adata.X` was type numpy.ndarray
when backed, `adata.X` is type <HDF5 dataset "X": shape (1000, 234), type "<i4">
when filename set to None `adata.X` is now NoneType

Is there a way to unset backed mode so `adata.X` is restored as an array?
Also, does this mean there is no file-backed (low memory usage) method to obtain the transpose of the data matrix?

**Comment by flying-sheep** [comment]
Unsetting backed mode is supported:

https://github.com/scverse/anndata/blob/5e5f57261dfc6531f69e682ae54682552ffc72eb/anndata/_core/anndata.py#L1053-L1055

Just do `adata.filename = None` or `del adata.filename`
