### ISSUE TITLE
Allow writing old version (<v0.7) of anndata?

### ISSUE THREAD

**Issue by nh3** [scverse/anndata#413]
Would you consider adding an option in AnnData.write() that allows saving as an old version (<v0.7) of h5ad file? There are still plenty of code relying on old version of scanpy/anndata around that cannot read v07.x h5ad. Happy to learn other workaround if you could kindly suggest. Many thanks!

**Comment by flying-sheep** [comment]
What do you mean “relying on old versions”? AFAIK we didn’t have much backwards compat breaking. Most code should work with the newest versions just fine. What exactly keeps you from updating?

**Comment by nh3** [comment]
For example, code relying on uns['neighbors'].

The frequent scenario is that a large chunk of the data is already analysed on a relatively old stack of programmes and then there comes some extra data in new anndata format that needs reprocessing and integration. Naturally one would hope there exists some convenient way of converting the new format to the old so that the extra data can be processed using the old software stack to maintain consistency.

**Comment by flying-sheep** [comment]
I mean, we’re trying to keep the API and analysis results backwards compatible. So I’d recommend to dockerize your old stack to be fully reproducible, then upgrade and continue analysis with the newest everything. Am I missing some reason why that’s not possible?

**Comment by nh3** [comment]
We have code that extended anndata's slot system, e.g. having multiple KNN graphs saved under uns by the name of, say, 'neighbors_A', 'neighbors_B', 'neighbors_C' with one of them being the set as active ('neighbors') at any point, and we have complex pipelines that relying on this feature for parameter exploration. Of course, obsp now provides a framework for doing that, but we don't want to migrate just yet. I almost started to implement a simple `write_legacy_h5ad()` function but just wanted to see if there is interest in having this feature in the anndata API. If not, than I am happy to use an ad hoc function. No worries.

**Comment by flying-sheep** [comment]
If it fits well into our API, it would be great to have:

1. Adding a `as_version` keyword argument to `write_h5ad` is the smallest problem.
2. `EncodingVersions` currently tracks the current version. We’d need to extend this system to know about the past versions (including the unencoded version before `obsp`, that therefore has to be inferred)
3. we shouldn’t clutter up the `h5ad` module too much, so it probably has to be split up. @ivirshup has a plan for that module and should know!

**Comment by ivirshup** [comment]
I'm not sure we can write pre 0.7 versions of anndata objects easily. This is something we can consider moving forward, but I think writing old versions could be more complicated than just reading old versions. 

That said, if you're storing the `"neighbors"` dicts under keys other than `"neighbors"`, I don't think any modification should happen on writing. Could you expand a bit more on where you're running into issues?

<details>
<summary> Example: no modifications </summary>

```python
import scanpy as sc
pbmc = sc.datasets.pbmc68k_reduced()

pbmc.uns["neighbors_a"] = pbmc.uns["neighbors"].copy()
pbmc.uns["neighbors_a"]["connectivities"] = pbmc.obsp["connectivities"]
pbmc.uns["neighbors_a"]["distances"] = pbmc.obsp["distances"] 

pbmc.write("tmp.h5ad")

from_disk = sc.read_h5ad("tmp.h5ad")
from_disk.uns["neighbors_a"]
# {'connectivities': <700x700 sparse matrix of type '<class 'numpy.float64'>'
#  	with 9992 stored elements in Compressed Sparse Row format>,
#  'distances': <700x700 sparse matrix of type '<class 'numpy.float64'>'
#  	with 6300 stored elements in Compressed Sparse Row format>,
#  'params': {'method': 'umap', 'n_neighbors': array([10])}}
```

</details>

**Comment by nh3** [comment]
Thanks for your reply. You are right, it looks like different `neighbors` keys under `uns` can be correctly handled by scanpy 1.5.x. We are now migrating to scanpy 1.5.x anndata 0.7.x (which requires quite a bit of modification to our existing code), but still there are reasons we want to keep running older version of scanpy/anndata in parallel, at least for a while. Anyway, what we care is to extract the "essential" slots from v0.7.x anndata, `X`, `obs`, `var`, and optionally `obsm`, into older version of scanpy/anndata for data integration and visualisation. I guess we can implement that outside the current version of anndata. Thank you for looking into this.

**Comment by ivirshup** [comment]
> which requires quite a bit of modification to our existing code

I'd be interested to know more about this, since we'd like upgrading to be painless. It'd be good to know where our blind spots are.

> Thank you for looking into this.

No problem!

**Comment by sjfleming** [comment]
I've run into the issue that `Seurat 3` will load the older version of h5ad files saved with `anndata < 0.7`, but it will not read new h5ad files saved with `anndata >=0.7`

It would be so great to be able to save in the old format to maintain easier interoperability between `scanpy` and `Seurat`.  `SeuratDisk` tries to solve this issue, but it only works with certain very new versions of `Seurat`, etc.  It would be easier for me if I could save an h5ad in the older `anndata < 0.7` format!

**Comment by sjfleming** [comment]
Or... if a change was made to allow `anndata 0.7+` to write an h5ad file that `Seurat 3.0.2` can load automatically.  (I care about Seurat 3.0.2 because, after that version, Seurat no longer works in a Jupyter notebook...)

**Comment by Zethson** [comment]
4 years later I am somewhat confident that people aren't interested in writing anndata < 0.7 anymore. If so, please comment again and we can reopen the issue.
