### ISSUE TITLE
Conda version old

### ISSUE THREAD

**Issue by adamgayoso** [scverse/anndata#435]
Just notifying you all that the version on conda is quite old.

https://anaconda.org/bioconda/anndata

I see you have a recipe on conda-forge, is there a way to remove the other one?

**Comment by ivirshup** [comment]
If we could, would we want to remove old versions? That could break older environments.

[Unfortunately](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html) the newest version won't always be installed:

> By default, conda prefers packages from a higher priority channel over any version from a lower priority channel.

Open to suggestions on this.

**Comment by adamgayoso** [comment]
I'm not much of a conda expert. I was testing out our recipe and only used `-c bioconda` and I believe it had installed the bioconda version of anndata, which was a bit confusing. Maybe the solution is to keep both up to date and only advertise conda-forge?
