### ISSUE TITLE
Non unique column names throw obscure error in concat

### ISSUE THREAD

**Issue by falexwolf** [scverse/anndata#483]
The following error is thrown as one AnnData object has two columns with the same name in `.obs`. It'd be great to have a better error message ("non-unique column names do not work with concat outer"):
![image](https://user-images.githubusercontent.com/16916678/102812073-b7225c00-43c6-11eb-8a48-41384d46604d.png)

**Comment by ivirshup** [comment]
Oh, yeah that's super unhelpful. 

Weird that pandas give's a much better error for non-unique indices (#480). This is an old open issue in pandas: https://github.com/pandas-dev/pandas/issues/6963
