### ISSUE TITLE
Add a writer for tuples

### ISSUE THREAD

**Issue by michalk8** [scverse/anndata#506]
Hi,

I'd like for a new writer to be registered for Python `tuples`, since lists are already supported.
Also, if possible/desired, would it be possible to extend this for `namedtuples` - it would need to save 2 additional metadata (the class name and the nametuple's attributes).

**Comment by ivirshup** [comment]
List are converted to arrays, and the arrays have to be homogenous and contain data that can be defined by a `dtype`, so I wouldn't exactly say lists are supported.

What are you trying to save exactly?

**Comment by michalk8** [comment]
I have a triple of dataframes and am using the namedtuples for convenience (instead of normal tuples/dictionary of dataframes).

**Comment by ivirshup** [comment]
We could maybe do a named tuple (would basically be represented as a dict with some metadata). I would have to think about the implications of this.

**Comment by giovp** [comment]
stumbled upon this, but going through a code review from @michalk8 I started to think that maybe `namedtuples` could a sound alternative to what we currently have in anndata for spatial metadata.

Right now, the way we store metadata is a nested dict which is quite ugly:
```python
spatial_key = "spatial"
library_id = "tissue42"
adata.uns[spatial_key] = {library_id: {}}
adata.uns[spatial_key][library_id]["images"] = {}
adata.uns[spatial_key][library_id]["images"] = {"hires": image}
adata.uns[spatial_key][library_id]["scalefactors"] = {"tissue_hires_scalef": 1, "spot_diameter_fullres": 0.5}
```

from example [here](https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_read_spatial.html)

with `namedtuple` we could standardize this across spatial technologies and make it easier for developers downstream. From a quick and shallow survey, the only affected so far would be us and the WIP over cellxgene https://github.com/chanzuckerberg/cellxgene/issues/2056

most of the other python libraries still do not really use the image, neither for plotting nor analysis. 

Thoughts? How hard would it be?

**Comment by ivirshup** [comment]
I agree that example sets the metadata in a weird way. I think something like this would be much cleaner:

```python
adata.uns[spatial_key] = {
    library_id: {
        "images": {"hires": image},
        "scalefactors": {"tissue_hires_scalef": 1, "spot_diameter_fullres": 0.5}
    }
}
```

But I'm not really why a `namedtuple` would be more useful than a `dict` here. You can still standardize on specific keys and values, but you can't add new values to a named tuple – which you'd probably want for different technologies.

------------

[PEP-589](https://www.python.org/dev/peps/pep-0589/) which lets you specify the structure of dicts with type annotations might be relevant here.

[`pydantic`](https://pydantic-docs.helpmanual.io) could also be used for this.

**Comment by ivirshup** [comment]
I'm going to close this as not planned.

It doesn't fit in the data model of our storage, and I don't think it adds enough value to burden other implementors with. I believe the proposed use case can be solved with parsing and schemas.

I think there could be value in storing structs..., but I'd want to see clear use cases.
