### ISSUE TITLE
Cannot concatenate a dataframe with other array types

### ISSUE THREAD

**Issue by gokceneraslan** [scverse/anndata#510]
Sorry I cannot write more details due to a deadline, but is this normal?

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/1140359/107959139-fd341000-6f70-11eb-91f9-3db3ca695c4c.png">

I will get back to this when I have more time, but just wanted to share.

**Comment by gokceneraslan** [comment]
OK, so apparently this happens when an obsm field in an anndata is a dataframe. I think this should be a warning though, not an error.

**Comment by ivirshup** [comment]
If it becomes a warning, what should it do? 

I left it as an error since I didn't think there was a single obvious way to concatenate a collection of arrays and dataframes. Should the result be an array or  a dataframe? `pandas` throws an error here.

I suppose just skipping the element could be a good option.

**Comment by bschilder** [comment]
@ivirshup @gokceneraslan 

I encountered this issue when I created the`obsm` data as a named list of data.frames in the R implementation of`anndata`, and then imported to python (which gets converted to a dict of `pd.DataFrame`s). Ran this across different chunks within the same Rmarkdown file.

### In R chunk 

```R
library(anndata)

seurat <- readRDS("raw_data/scRNAseq/Raj2018/GSE105010_fall.inDrops.seuratv3.rds")
EWCE:::assign_cores()

# library(sceasy)
# library(SingleCellExperiment)
# adat <- sceasy::convertFormat(seurat, from = "seurat", "anndata")

raw <- seurat@assays$RNA@counts
obs = seurat@meta.data[colnames(raw),]
var = data.frame("gene"=row.names(seurat@assays$RNA@counts), row.names = row.names(seurat@assays$RNA@counts))
uns = list("var.features"=seurat@assays$RNA@var.features)
obsm = list("pca"=data.frame(seurat@reductions$pca@cell.embeddings)[colnames(raw),], 
            "tsne"=data.frame(seurat@reductions$tsne@cell.embeddings)[colnames(raw),]
           )   
```

### Then in Python chunk

```python
from scipy import sparse 
import anndata as ad 
  
adat = ad.AnnData(X=r.raw.transpose(), obs=r.obs, obsm=r.obsm, var=r.var, uns=r.uns)  
adat.write("raw_data/scRNAseq/Raj2018/Raj2018.h5ad")
```

My solution was to take the values from the dataframe and reassign it. So I suppose you could add a bit of code that detects whether each`obsm` item is a `pd.DataFrame`, and if it is, convert it like so:

```python
adat.obsm["pca"] = adat.obsm["pca"].values
```
