### ISSUE TITLE
Multimodal Data

### ISSUE THREAD

**Issue by atarashansky** [scverse/anndata#515]
Hi there. I’m working on extending SAM to allow joint integration of multimodal datasets. For SAM, I refactored the code to work with a dictionary of ‘assays’, where each assay is a separate AnnData. This works well-enough, but it’s kind of a headache to output the associated h5ad files since I need to make one for each assay.

It would be really great if an AnnData could encapsulate multiple AnnData’s, via something similar to the `.raw` attribute. 

AnnData could have a default assay: this is default AnnData (`adata`), the contents of which will be displayed if we output it in a Jupyter cell, for example. Other assays (including an inplace reference to the default AnnData) will be stored as attributes (e.g. `adata.rna`, `adata.atac`, `adata.cite`, etc), with assay names specified by the user as they load the data. The user should also be able to change which assay is the default assay.

I’m not too familiar with the inner-workings of AnnData, is something like this possible?

**Comment by atarashansky** [comment]
I just saw the discussion in #237.

I think this solution could work very well (assuming there are no obvious implementation obstacles that I’m unaware of) as none of the functions in scanpy/anndata would have to be modified — they would just automatically operate on whatever assay is specified as default. If the user wants to change what AnnData the functions operate on, they would just switch the identity of the default assay.

**Comment by flying-sheep** [comment]
Hi, thanks for that PR and this discussion. I’m going to close this in favor of #237

If we reconsider multimodal support in AnnData, it will be talked about there.
