### ISSUE TITLE
`chunks` for sparse Matrix types

### ISSUE THREAD

**Issue by ilan-gold** [scverse/anndata#524]
Would it be posssible to allow for the `chunks` argument in `write_zarr` to be applied to sparse matrices as well?  The chunks can be rather large at the moment, especially for `data`.  Thanks!
Like this:
https://github.com/theislab/anndata/blob/2723c9c9e8bc0fe50a9513f292916616a603923b/anndata/_io/zarr.py#L48-L51

**Comment by ilan-gold** [comment]
I would be willing to make a PR for this if you would be interested, less willing for #523 due to its complexity (i.e sparse `layers` but not sparse `X` for example).

**Comment by ilan-gold** [comment]
I'm going to make a PR for this if that's all right.

**Comment by ilan-gold** [comment]
Just opened https://github.com/theislab/anndata/pull/568

**Comment by flying-sheep** [comment]
Supported by SparseCompressedDataset if I understand correctly
