### ISSUE TITLE
what is the best way to replace adata.X with another matrix?

### ISSUE THREAD

**Issue by YubinXie** [scverse/anndata#559]
Hi anndata team,

I am trying to work with both raw count matrix and normed data. So I hope to do something like anndata.X = anndata.obsm['raw'].copy(). However, this process is super slow. 

I tried anndata.X.data = anndata.obsm['raw'].copy() and it does not really work. Do you have any suggestion on this? Thanks!

**Comment by ivirshup** [comment]
Is the object on the left hand side a view? If not, I don't see why this would be slow. An example of a profile or some timings could be useful for us to know what you're seeing.

But, this seems fine:

```python
pbmc = sc.datasets.pbmc3k_processed().raw.to_adata()
pbmc.layers["counts"] = sc.datasets.pbmc3k()[pbmc.obs_names, pbmc.var_names].X.copy()

%timeit pbmc.X = pbmc.layers["counts"]
# 2.46 ms ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by YubinXie** [comment]
oh, by view you meant, if anndata is a subset of another data, by anndata= ad1[:,:], it will be very slow? I think this could be the issue. shall I do anndata= ad1[:,:].copy() in this case?

**Comment by ivirshup** [comment]
That could make it slow, but it would be useful to see what your case is and what the timing are.

**Comment by YubinXie** [comment]
i took 50k cells x 20k gene from 83k cellsx 20k gene, and performed the assignment. it took more than an hour...

**Comment by ivirshup** [comment]
That definitely seems wrong.

* Was the assignment target a view? If so, did making a copy help?
* Did you get any warnings during this?

**Comment by YubinXie** [comment]
> That definitely seems wrong.
> 
> * Was the assignment target a view? If so, did making a copy help?
> * Did you get any warnings during this?

1. Yes, it is a view. and making a copy helps.

2. There is warning when I generate the view but no warning when I assign the matrix to view.X
3. 
`/home/xiey/miniconda3/envs/scrna/lib/python3.8/site-packages/pandas/core/arrays/categorical.py:2487: FutureWarning: The `inplace` parameter in pandas.Categorical.remove_unused_categories is deprecated and will be removed in a future version.
  res = method(*args, **kwargs)
`
