### ISSUE TITLE
How to split a gene into 2 genes based on the `anndata.obs['sample']` values?

### ISSUE THREAD

**Issue by danli349** [scverse/anndata#586]
Hello,

Can someone help me and tell me how to split a gene into 2 genes based on the `anndata.obs['sample']` values?
Because there are 2 transgenic genes and most of the sequences are the same, which can't be separated during alignment. 
Those 2 genes are in different samples so I want to split them in the `anndata` file. Thanks a lot.

Best
Dan

**Comment by flying-sheep** [comment]
See here: https://stackoverflow.com/a/58645591/247482
