### ISSUE TITLE
Combine loom Objects and Force-rename Cells

### ISSUE THREAD

**Issue by angelussong** [scverse/anndata#618]
Hi,![image](https://user-images.githubusercontent.com/40570906/133642788-b948c6f2-15ad-4e36-9d4b-8aec799ab641.png)
I am planning to run scvelo on six samples which were already merged, QC-ed and analyzed in Seurat. And I've successfully generated the loom objects using velocyto for each sample using the aligned bam files as well as the barcode lists I generated from the merged Seurat object.

But when I tried to use adata.concatenate(), the total number of cells did not match what I had in the Seurat objects. Individually, each loom object matched what I had for each sample. But together the number was off.
These are the individual loom objects.
![image](https://user-images.githubusercontent.com/40570906/133642788-b948c6f2-15ad-4e36-9d4b-8aec799ab641.png)
These are the number of cells from my Seurat object:
![image](https://user-images.githubusercontent.com/40570906/133642867-7ece2041-164f-4bdc-94f1-36bed417ce98.png)

However, after combination (adata=adata.concatenate(adata_VC1,adata_VC2,adata_VE1,adata_VE2,adata_VR1,adata_VR2)), I have 3481 cells where I should only have 2723 cells. I don't really understand the cause of this. Would you please help me with this?

And another issue is that I did not have individual Seurat objects/h5ad objects for each sample so I need to have a combined loom object where I could also import in the UMAP coordinates and annotation IDs. But Seurat has forced renaming the cells to prevent duplicate cell IDs. I am wondering if there is any way for me to force renaming the cells for each loom objects before combining them and then transfer the metadata from my combined Seurat/h5ad object to it so that all the cell IDs could match?

Thanks so much!

**Comment by flying-sheep** [comment]
Since therewas no follow-up I’m going to close this. Please comment if this is still an issue, and we can reopen
