### ISSUE TITLE
Nullable string columns

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#679]
Split off from #504

It would be nice to have support for nullable string arrays. It would be good to have a consistent in-memory representation for these so we can reason about performance. However, this does not currently exist in our dependency stack. I currently think this feature will be dependent on upstream developments in pandas StringArray type.

This is less urgent than nullable integers and booleans since we already have nullable categorical arrays, and currently aggressively cast strings to categorical for performance reasons.

**Comment by ivirshup** [comment]
Pandas now has multiple ways of doing strings, custom and via arrow.

I think we could still handle both these cases by just storing a mask. This would just be a little inefficient, but we can always update.

This would require implementing the arrow mask handling in anndata.

**Comment by ivirshup** [comment]
This issue wouldn't apply for rank genes groups because that object is a record array, while this issue addresses dataframe columns specifically.

**Comment by pcm32** [comment]
No problem, should I open a new one here or on scanpy?

**Comment by ivirshup** [comment]
@pcm32, sorry for the late response here. Came at a busy time of year.

I believe there will already be issues open on scanpy for this.

**Comment by nroak** [comment]
Thank you for this update, is there an estimated timeline for this issue to be patched? I'm facing it exactly where you explained- due to nan in ranked gene lists.

**Comment by flying-sheep** [comment]
OK, to be clear: This issue means support for `pandas.core.arrays.string_.StringArray` as described in #963, right?

**Comment by MishalAshraf** [comment]
had a similar issue when trying to concatenate objects. one dataset has a boolean obs column, the other does not. when they are combined it becomes True/False/NaN. I agree that it's up to the user to determine and explicitly define how they want to handle this. 

For me, this is 1 step in a longer pipeline for data exploration. It would be nice to have a lazy save here where I concatenate multiple datasets without explicitly resolving which columns will be informative later on.

**Comment by flying-sheep** [comment]
milestone was missed, bumping to 0.10.0

**Comment by flying-sheep** [comment]
Pandas seems to get a dedicated string array type (the vote is pretty much in favor), but it’s *not* based on the [nullable string array in numpy 2](https://numpy.org/doc/stable/user/basics.strings.html#missing-data-support) :facepalm: 

- https://github.com/pandas-dev/pandas/pull/58551
- https://github.com/pandas-dev/pandas/issues/58503

**Comment by ilan-gold** [comment]
Potential solution (also going forward): use `settings`!

**Comment by flying-sheep** [comment]
To expand on it: We want opt-in writing so people don’t accidentally write files that can’t be read by most people.

So we’d add a setting that enables writing `pd.StringDtype` series, and if one of them is encountered without the setting being active, we throw an error that explains how to enable it and why it’s disabled by default.
