### ISSUE TITLE
Suprising behaviour with .raw and var/obs indexing

### ISSUE THREAD

**Issue by morris-frank** [scverse/anndata#692]
Hey,

a really simple observation, which led to some surprising behavior, assume we have an anndata object `ad` with

```py
ad.shape == (1_000, 10_000)
```

now if I index with a subset of `.var` or `.obs` and access `.raw` I get different results, and am not sure if this is expected behavior:

```py
ad[ad.obs_names[:100], :].raw.shape == (1_000, 10_000)
ad[ad.obs_names[:100], :].raw.X.shape == (100, 10_000)
ad[:, ad.var_names[:100]].raw.shape == (1_000, 10_000)
ad[:, ad.var_names[:100]].raw.X.shape == (1_000, 10_000)
```

So, the `.raw` shape is only adapted with `.obs` indexing, but also there the `raw.shape` doesn't reflect the shape of the matrix.

Maybe this is expected behavior, but it was surprising to me.

AnnData is version `0.7.8`

**Comment by flying-sheep** [comment]
The documentation explains the behavior and at least hints at the rationale: https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.raw.html

<img width="1093" alt="image" src="https://github.com/scverse/anndata/assets/291575/dd7c3db2-d258-40c4-9b43-f24bb9918ca3">
