### ISSUE TITLE
Tests fail with pandas==1.4.1

### ISSUE THREAD

**Issue by joshua-gould** [scverse/anndata#709]
Tests in test_backed_sparse.py, test_hdf5_backing.py, test_inplace_subset.py, test_views.py fail with pandas 1.4

**Comment by ivirshup** [comment]
I can't reproduce locally, could you share some more about your environment?

**Comment by joshua-gould** [comment]
Attached output from conda env export. Thanks.
[environment.yml.txt](https://github.com/theislab/anndata/files/8092523/environment.yml.txt)

**Comment by flying-sheep** [comment]
We’re far past pandas 1.4, so I’m closing this.
