### ISSUE TITLE
from anndata import AnnData fails with flit

### ISSUE THREAD

**Issue by falexwolf** [scverse/anndata#733]
In one instance of treating anndata as a dependency within flit, I now get:
```
from anndata import AnnData
-> ImportError: cannot import name 'AnnData' from 'anndata'
```
When I replace the import as follows
```
from anndata._core.anndata import AnnData
```
it all works fine again.

I vaguely remember we had these name resolution errors many years ago. I post this mostly for reference if someone else needs this workaround.

No action is necessary.

**Comment by ivirshup** [comment]
> In one instance of treating anndata as a dependency within flit

I'm not sure what you mean here. Could you clarify?

**Comment by falexwolf** [comment]
I think `pip install -e` doesn't recognize extras like `doc, test` when they're in `pyproject.toml`. Or am I getting something wrong?

```
pip install -e .[doc]
```

This also fails here on anndata despite being defined in https://github.com/theislab/anndata/blob/master/pyproject.toml.

**Comment by ivirshup** [comment]
That works for me. What's particularly weird for me is that it doesn't fail when the `"extras"` doesn't exist.

Maybe a newer `pip` is needed?

**Comment by flying-sheep** [comment]
> ```
> pip install -e .[doc]
> ```

this should work. If you use zsh (default on macOS), `[` is shell syntax though. What if you try:

```
pip install -e '.[doc]'
```

**Comment by falexwolf** [comment]
Thank you, Phil! I think it was indeed just a lack of escaping `[`.

pip now works for me.
