### ISSUE TITLE
Support for scipy sparse arrays

### ISSUE THREAD

**Issue by ivirshup** [scverse/anndata#746]
Apparently scipy now has [sparse arrays with array indexing](https://docs.scipy.org/doc/scipy/reference/sparse.html)?

Unfortunately they do seem to inherit from the matrix classes, which makes checking their types a bit fraught.

**Comment by arogozhnikov** [comment]
actually that would be awesome if anndata was providing new sparse arrays not matrices. I find it very hard and annoying to memorize how things are working in sparse matrices. As an idea that should be easy to implement and will not break downstream projects:

```python
# setter that internally converts sparse array into a matrix
ad.X_sparr = some_sparse_array 

# getter that converts X into sparse csc_array 
ad.X_sparr
```

Eventually I believe you want to migrate internals of anndata to manipulate arrays not matrices.

**Comment by ivirshup** [comment]
I think we are going to hold off on this until there is better support in the broader ecosystem for these classes. E.g. until scikit-learn can use these, it's difficult to recommend them. At that point we can quickly move to automatically reading these at IO time.

**Comment by arogozhnikov** [comment]
unstale this. Still waiting for bright moment of sparse arrays
