### ISSUE TITLE
Warning with rename_categories()

### ISSUE THREAD

**Issue by perrin-isir** [scverse/anndata#748]
Using `rename_categories()` gives a warning, because it uses the inplace=True option in the pandas function rename_categories(), which is deprecated, see: 
https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.rename_categories.html

The warning:
```
FutureWarning: The `inplace` parameter in pandas.Categorical.rename_categories is deprecated and will be removed in a future version. Removing unused categories will always return a new Categorical object.
```

**Comment by ivirshup** [comment]
Thanks for id-ing this. Should be fixed by #790
