### ISSUE TITLE
cannot open a loom file

### ISSUE THREAD

**Issue by shambam** [scverse/anndata#754]
- [ y] I have checked that this issue has not already been reported.
- [y ] I have confirmed this bug exists on the latest version of scanpy.
- [ ] (optional) I have confirmed this bug exists on the master branch of scanpy.

---

I'm trying to load a loom file that was made using "loompy fromfq". I've connected to the loom file using loompy to check everything is there which is appears to be, but scanpy will not load it.

I should add I'm not a Python expert.

### Minimal code sample (that we can copy&paste without having any data)

```python
import scanpy as sc

s9 = sc.read_loom("S9.loom")

```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [15], in <cell line: 1>()
----> 1 s9 = sc.read_loom("S9.loom")

File ~/anaconda3/envs/scanpy.env/lib/python3.9/site-packages/anndata/compat/__init__.py:305, in _deprecate_positional_args.<locals>._inner_deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
    303 extra_args = len(args) - len(all_args)
    304 if extra_args <= 0:
--> 305     return f(*args, **kwargs)
    307 # extra_args > 0
    308 args_msg = [
    309     "{}={}".format(name, arg)
    310     for name, arg in zip(kwonly_args[:extra_args], args[-extra_args:])
    311 ]

File ~/anaconda3/envs/scanpy.env/lib/python3.9/site-packages/anndata/_io/read.py:271, in read_loom(filename, sparse, cleanup, X_name, obs_names, obsm_names, var_names, varm_names, dtype, obsm_mapping, varm_mapping, **kwargs)
    269 # TODO: Figure out the singleton obs elements
    270 obs, obsm = _fmt_loom_axis_attrs(dict(lc.col_attrs), obs_names, obsm_mapping)
--> 271 var, varm = _fmt_loom_axis_attrs(dict(lc.row_attrs), var_names, varm_mapping)
    273 uns = {}
    274 if cleanup:

File ~/anaconda3/envs/scanpy.env/lib/python3.9/site-packages/anndata/_io/read.py:149, in _fmt_loom_axis_attrs(input, idx_name, dimm_mapping)
    146     axis_mapping[key] = np.array([input.pop(name) for name in names]).T
    148 for k, v in input.items():
--> 149     if v.ndim > 1 and v.shape[1] > 1:
    150         axis_mapping[k] = v
    151     else:

AttributeError: 'NoneType' object has no attribute 'ndim'

```

#### Versions

<details>

[Paste the output of scanpy.logging.print_versions() leaving a blank line after the details tag]

-----
anndata     0.8.0
scanpy      1.9.1
-----
PIL                 9.1.0
asttokens           NA
backcall            0.2.0
beta_ufunc          NA
binom_ufunc         NA
cffi                1.15.0
cycler              0.10.0
cython_runtime      NA
dateutil            2.8.2
debugpy             1.6.0
decorator           5.1.1
defusedxml          0.7.1
entrypoints         0.4
executing           0.8.3
h5py                3.6.0
hypergeom_ufunc     NA
igraph              0.9.10
ipykernel           6.13.0
ipython_genutils    0.2.0
jedi                0.18.1
joblib              1.1.0
jupyter_server      1.16.0
kiwisolver          1.4.2
leidenalg           0.8.9
llvmlite            0.38.0
loompy              3.0.7
matplotlib          3.5.1
matplotlib_inline   NA
mpl_toolkits        NA
natsort             8.1.0
nbinom_ufunc        NA
numba               0.55.1
numpy               1.21.5
numpy_groupies      0.9.14
packaging           21.3
pandas              1.4.2
parso               0.8.3
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
prompt_toolkit      3.0.29
psutil              5.9.0
ptyprocess          0.7.0
pure_eval           0.2.2
pycparser           2.21
pydev_ipython       NA
pydevconsole        NA
pydevd              2.8.0
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pygments            2.11.2
pyparsing           3.0.8
pytz                2022.1
scipy               1.8.0
scvelo              0.2.4
session_info        1.0.0
setuptools          62.1.0
six                 1.16.0
sklearn             1.0.2
stack_data          0.2.0
texttable           1.6.4
threadpoolctl       3.1.0
tornado             6.1
traitlets           5.1.1
typing_extensions   NA
wcwidth             0.2.5
zmq                 22.3.0
-----
IPython             8.2.0
jupyter_client      7.2.2
jupyter_core        4.9.2
jupyterlab          3.3.3
notebook            6.4.10
-----
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:22:55) [GCC 10.3.0]
Linux-5.4.0-107-generic-x86_64-with-glibc2.31
-----
Session information updated at 2022-04-12 14:22

</details>

**Comment by ivirshup** [comment]
Thanks for the report. I've moved this to anndata since that's where `read_loom` is implemented.

`loompy fromfq` uses `kallisto`, right? Have you checked if you're using the most recent version of `kallisto`?

**Comment by shambam** [comment]
> Thanks for the report. I've moved this to anndata since that's where `read_loom` is implemented.
> 
> `loompy fromfq` uses `kallisto`, right? Have you checked if you're using the most recent version of `kallisto`?

Yup, I installed everything from scratch into a new conda env.

**Comment by shambam** [comment]
> As a work around, I believe [`bustools` can output a h5ad](https://www.kallistobus.tools/kb_usage/kb_count/). Would it be possible to do that instead of going through `loom`?

I could for sure. I used loompy fromfq a while back which worked well which is why I used it again, but yes, kallisto will do the job. Many thanks.

**Comment by ivirshup** [comment]
Its not obvious to me that the bug here is in anndata.

I think I'm going to close this, but will re-open if there's evidence to the contrary.
