### ISSUE TITLE
Subsetting anndata

### ISSUE THREAD

**Issue by J1205** [scverse/anndata#766]
Hi,

I wonder how am I able to select(row) or filter(column) out the anndata. For example, hope to collect the cells based on the certain clusters labeled as 1 and 2 after applying a Louvain or Leiden algorithm. Could you please give me a piece of advice? 

Thank you in advance for your kind help..!

**Comment by Zethson** [comment]
Hi,

please ask usage questions on Discourse: https://discourse.scverse.org/

Have you checked out the tutorial yet? https://anndata-tutorials.readthedocs.io/en/latest/getting-started.html It also has a small section on subsetting.

**Comment by J1205** [comment]
Hi, @Zethson 

Thanks a lot for your comments. I found .isin() function could be very helpful. 

https://scanpy.discourse.group/t/filter-out-specific-clusters-using-their-cluster-number/82
