### ISSUE TITLE
AttributeError: 'Dataset' object has no attribute 'asstr'

### ISSUE THREAD

**Issue by JBreunig** [scverse/anndata#771]
I cannot load cached or even newly saved h5ad files with anndata 0.8.0.  I am continually getting:
AttributeError: 'Dataset' object has no attribute 'asstr'

Is this related to #691 
h5py version is 3.6.0

**Comment by ivirshup** [comment]
Can you provide a full traceback? It would also be good if you could show `h5py.__version__` in the same python session where you see this error.

**Comment by JBreunig** [comment]
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
Type "copyright", "credits" or "license" for more information.

IPython 8.3.0 -- An enhanced Interactive Python.


import numpy as np
import pandas as pd
import scanpy as sc
import scanpy.external as sce

import scvelo as scv
import seaborn as sns
import loompy
import os, sys
import velocyto as vcy
# import os
os.environ["R_HOME"] = "/bin/R"
import infercnvpy

# import pyreadr

sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
# sc.logging.print_versions()
sc.settings.set_figure_params(dpi=600, dpi_save=600, color_map='OrRd')
sc.settings.set_figure_params(dpi=100, dpi_save=100, color_map='OrRd')

# sc.settings.n_jobs = 56

os.getcwd()
os.chdir('/mnt/2TBWDMuDev2Underside20620/JabadoTaylor/')  ##Cerebellum Development



SN006 = sc.read('/mnt/2TBWDMuDev2Underside20620/HeidelbergCerebellumLooms/SN006.loom', var_names='var_names', obs_names='obs_names', cache=True, validate=False)
reading from cache file cache/mnt-2TBWDMuDev2Underside20620-HeidelbergCerebellumLooms-SN006.h5ad
Traceback (most recent call last):

  Input In [1] in <cell line: 29>
    SN006 = sc.read('/mnt/2TBWDMuDev2Underside20620/HeidelbergCerebellumLooms/SN006.loom', var_names='var_names', obs_names='obs_names', cache=True, validate=False)

  File ~/anaconda3/lib/python3.8/site-packages/scanpy/readwrite.py:112 in read
    return _read(

  File ~/anaconda3/lib/python3.8/site-packages/scanpy/readwrite.py:734 in _read
    return read_h5ad(path_cache)

  File ~/anaconda3/lib/python3.8/site-packages/anndata/_io/h5ad.py:236 in read_h5ad
    d[k] = read_dataframe(f[k])

  File ~/anaconda3/lib/python3.8/site-packages/anndata/_io/h5ad.py:301 in read_dataframe
    return read_elem(group)

  File ~/anaconda3/lib/python3.8/site-packages/anndata/_io/specs/registry.py:183 in read_elem
    return _REGISTRY.get_reader(type(elem), get_spec(elem), frozenset(modifiers))(elem)

  File ~/anaconda3/lib/python3.8/site-packages/anndata/_io/specs/methods.py:524 in read_dataframe
    index=read_elem(elem[idx_key]),

  File ~/anaconda3/lib/python3.8/site-packages/anndata/_io/specs/registry.py:183 in read_elem
    return _REGISTRY.get_reader(type(elem), get_spec(elem), frozenset(modifiers))(elem)

  File ~/anaconda3/lib/python3.8/site-packages/anndata/_io/specs/methods.py:327 in read_string_array
    return read_array(d.asstr())

AttributeError: 'Dataset' object has no attribute 'asstr'

**Comment by JBreunig** [comment]
Regarding the h5py, it came back as 2.10.0 in Spyder, which is probably causing the problem.  I'm going to clear Anaconda and reinstall everything.  And that was after I explicitly imported it with import h5py...otherwise, the version command didn't work.

**Comment by JBreunig** [comment]
After reinstall, all is fine and h5py is >3.3 in spyder.
