### ISSUE TITLE
plot different sample regions and different age groups from AnnData

### ISSUE THREAD

**Issue by mostafa-ti** [scverse/anndata#773]
Hi,
My data contain three different regions from the mouse brain, which were dissected from three age groups. So I have nine different samples in my Anndata coming from cellranger pipeline output (barcodes.tsv.gz, features.tsv.gz, matrix.mtx.gz). How can I plot each of these groups separately?
Any help will be appreciated.

**Comment by Zethson** [comment]
Hi,

please ask usage questions in our forums: https://discourse.scverse.org/
