### ISSUE TITLE
suddenly unable to read .h5ad file

### ISSUE THREAD

**Issue by parkjooyoung99** [scverse/anndata#780]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/77565848/172306765-fa6bbc92-185b-41ed-bbaf-0fa97f9b07c0.png">

there were no problem reading .h5ad file but all of the sudden, this error came up and unable to read .h5ad files,, 

someone have any idea??

Thank you!!

**Comment by flying-sheep** [comment]
It was probably written by a newer anndata version. Try updating anndata, maybe that helps.

We have a PR that improves error messages in this regard. @ivirshup could you please merge or adapt and then merge #734?

**Comment by parkjooyoung99** [comment]
Thanks for your help! I have updated anndata and h5py and re-start my jupyter noteobok and it works!!
