### ISSUE TITLE
"AnnData.concatenate" discards parts of the .raw attribute

### ISSUE THREAD

**Issue by watiss** [scverse/anndata#783]
In reference to #263

I am facing a similar issue now. I am concatenating two identical anndatas (as a test). They have the same var dataframe under `adata.raw.var` and `adata2.raw.var`. However, `adata3`, which is the results of `adata3 = adata.concatenate(adata2, join="outer")` has a dataframe in `adata3.raw.var` that is missing the columns (only the index is there). Is this expected?

**Comment by tiannagrant** [comment]
I am facing the same issue. Maybe I'm missing fundamental anndata concepts but after subsetting anndata object by sample then performing basic QC, I concat the subsetted object but the ouput deletes the var attribute. So no 'gene_ids', 'feature_types'. Help would be nice.

**Comment by flying-sheep** [comment]
Please use [`anndata.concat`](https://anndata.readthedocs.io/en/latest/concatenation.html)
