### ISSUE TITLE
Anndata.concat([adata1, adata2, ...]) not working as expected

### ISSUE THREAD

**Issue by mahati-acog** [scverse/anndata#798]
Hi

I am trying to concatenate multiple anndata objects into one. If I consider axis=0, it is combining along .obs and if I consider axis=1, it is combining along .var. But I want to get all the elements in one final anndata object without missing any elements of anndata object.

**Comment by Zethson** [comment]
Could you provide a minimal example setup of this and the expected output?

**Comment by cqbsyn** [comment]
Hi, did you solve this problem？

**Comment by ivirshup** [comment]
Without more details, it's difficult to tell what exactly should happen here. Most use cases I can think of here should be possible by passing `join="outer"`.

I'm going to close this, but can reopen given more details.
