### ISSUE TITLE
Changes to obs do not flush to file in backed-mode

### ISSUE THREAD

**Issue by jeskowagner** [scverse/anndata#811]
Hi,

Sorry for creating so many issues these days.

This issue is aimed at handling changes to `obs` in backed mode. Specifically, I noticed that changes to `obs` to not get flushed to file by `AnnData.file.close()`. Is there a better way to ensure the object and file are synchronized? The anndata version used here is `0.8.0`.

Example:
```python
import anndata
import numpy as np
import pandas as pd

tmp_file = "tmp.h5ad"

# create a dummy file, write it to disk
adata = AnnData(X = np.random.random((10,10)),
                             obs = pd.DataFrame({"group":np.random.randint(0,2,10)}))

adata.write(tmp_file)

# load in dummy file in backed mode, add column to obs, then close file
adata_copy = anndata.read_h5ad(tmp_file, backed="r+")
adata_copy.obs["group2"] = np.random.randint(0,2,10)
adata_copy.file.close()

# read in file to check whether group2 is present
anndata.read_h5ad(tmp_file)
# AnnData object with n_obs × n_vars = 10 × 10
#   obs: 'group'
```

**Comment by ivirshup** [comment]
`backed` mode currently only has an effect on `.X`. This is partially because some specific semantics only work then, but also because providing a pandas like interface to a backed dataframe is hard.

**Comment by jeskowagner** [comment]
Good to know! This was a "gotcha" for me - perhaps someone/I can draft a little page for the documentation explaining `backed` mode to clarify what it does and does not do?

**Comment by jeskowagner** [comment]
Sure, I'll try and find time soon! Would you prefer a separate page or should the explanation be in the docstring of `read_h5ad`?

**Comment by jeskowagner** [comment]
Closing this in favor of discussion at #812.
