### ISSUE TITLE
`AnnData._inplace_subset_var` deletes entries in `AnnData.uns`

### ISSUE THREAD

**Issue by WeilerP** [scverse/anndata#849]
## Description

Using `AnnData._inplace_subset_var`, entries in `.uns` are deleted if

1. There is a categorical column (let's say `"col_1"`)
2. `.uns` has the key `"col_1_colors"` and the corresponding value is a list

For example:

```python
import numpy as np
from anndata import AnnData

adata = AnnData(np.eye(5), uns={'col_1_colors': [0, 1, 2], 'col_2_colors': 5})
adata.obs['col_1'] = ['d1', 'd1', 'd1', 'd2', 'd2']
adata.obs['col_1'] = adata.obs['col_1'].astype('category')
adata.obs['col_2'] = ['s1', 's2', 's2', 's1', 'd2']
adata.obs['col_2'] = adata.obs['col_2'].astype('category')

adata._inplace_subset_var(np.ones(adata.n_vars, dtype=bool))
adata
```

I would expect the resulting `AnnData` to be unchanged, _i.e._

```bash
AnnData object with n_obs × n_vars = 5 × 5
    obs: 'col_1', 'col_2'
    uns: 'col_1_colors', 'col_2_colors'
```

but it is

```bash
AnnData object with n_obs × n_vars = 5 × 5
    obs: 'col_1', 'col_2'
    uns: 'col_2_colors'
```

Note that the same behavior happens if the subsetting is done on the rows with a mask, _e.g._

```python
adata = adata[np.logical_and(adata.obs['col_1'].isin(['d1']), adata.obs['col_2'].isin(['s1'])), :].copy()
```

## Package versions

I used Python 3.9, with `anndata==0.8.0`, `h5py==3.7.0`, `natsort==8.2.0`, `numpy==1.23.5`, `packaging==21.3`, `pandas=1.5.1` `pyparsing==3.0.9`, `python-dateutil==2.8.2`, `pytz==2022.6`, `scipy==1.9.3`, `six==1.16.0`.

**Comment by WeilerP** [comment]
@ivirshup, any idea what's causing this? I presume it's not the expected behavior?

**Comment by WeilerP** [comment]
Similarly, keys `"col_colors"` with dictionaries as values are turned into an array containing the dictionary:

```
adata.uns['col_1_colors'] = {'b': 0, 'c': 3}]
```

becomes

```
array([{'b': 0, 'c': 3}], dtype=object)
```

**Comment by lvzenglei** [comment]
> @WeilerP, this is the logic used to remove unused categories but keep category clusters colors. The same things would happen when subsetting by obs.
> 
> I agree the logic isn't ideal.
> 
> Is this causing a specific problem downstream?



> @WeilerP, this is the logic used to remove unused categories but keep category clusters colors. The same things would happen when subsetting by obs.
> 
> I agree the logic isn't ideal.
> 
> Is this causing a specific problem downstream?

I add obs key {vdj4} in obs with h5py packages, and I can find this key.  but when I read h5ad with scanpy (anndata) ,this key disappear , how can solve it?
`>>> file = h5py.File('/home/lvzenglei/repo/vdj_test/test/c1642_fig_merge_fig_4I_1_4I_2_Tcell_cat.h5ad','a')
>>> data = file['/obs/annot_full']
>>> data2 = file['/obs/__categories/annot_full']
>>> file.create_dataset('/obs/vdj4',data=data)
<HDF5 dataset "vdj4": shape (18775,), type "|i1">
>>> file.create_dataset('/obs/__categories/vdj4',data=data2)
<HDF5 dataset "vdj4": shape (3,), type "|O">
>>> file['/obs'].keys()
<KeysViewHDF5 ['Disease', 'Disease subtype', 'Drug', 'If sorted', 'Model used', 'Organ', 'Patient ID', 'Sample ID', 'Sample type', 'Species', 'Tissue', 'Treatment', 'Type of treatment', '__categories', '_index', 'annot_full', 'cluster', 'n_genes', 'orig.ident', 'pct_counts_mito', 'total_counts', 'vdj2', 'vdj3', 'vdj4']>
>>> file.close()`



`>>> import scanpy as sc
sc.radata = sc.read('/home/lvzenglei/repo/vdj_test/test/c1642_fig_merge_fig_4I_1_4I_2_Tcell_cat.h5ad')
adat>>> adata.obs.keys()
Index(['orig.ident', 'total_counts', 'n_genes', 'pct_counts_mito', 'cluster',
       'Sample ID', 'Patient ID', 'annot_full', 'Species', 'Model used',
       'Organ', 'Tissue', 'If sorted', 'Disease', 'Disease subtype',
       'Sample type', 'Treatment', 'Type of treatment', 'Drug'],
      dtype='object')`

**Comment by flying-sheep** [comment]
This seems to be caused by this scanpy specific functionality that snuck into anndata:

https://github.com/scverse/anndata/blob/d346beb7d53ef4e8b4ebbc9da17ff70c64cf5293/anndata/_core/anndata.py#L1118-L1131

that code is part of `_remove_unused_categories`, which itself is slated to be deprecated or removed: #890

@ivirshup we should move the treatment of `color` stuff into scanpy, do you agree?

**Comment by WeilerP** [comment]
@ivirshup, @flying-sheep, @ilan-gold, is there any news on this issue? It's becoming increasingly annoying to always have to  take care of fields in `.uns`. The conversion from a dictionary to an array, for example, causes issues when saving the AnnData object. I agree with @flying-sheep, that I do not think this is a case that should be handled in anndata. As far as I am aware of, you also do not reset categories, when subsetting a categorical column, for example.

**Comment by ilan-gold** [comment]
@WeilerP The "reset" (or not) of columns in dataframes is coming in `0.11` as a setting.  So I _think_ (looking briefly at the code) that this will be resolvable soon, although then you'll have extra categories on the dataframe that may not be present anymore.  But I think this is generally acceptable (not sure what the big deal would be unless you're looking at the categories directly).

**Comment by WeilerP** [comment]
> @WeilerP The "reset" (or not) of columns in dataframes is [coming in `0.11` as a setting](https://github.com/scverse/anndata/blob/main/docs/release-notes/0.11.0.md). So I _think_ (looking briefly at the code) that this will be resolvable soon, although then you'll have extra categories on the dataframe that may not be present anymore. But I think this is generally acceptable (not sure what the big deal would be unless you're looking at the categories directly).

Okay, good to hear! And the feature carries over from `.obs` to also not mess with `.uns`?

**Comment by ilan-gold** [comment]
Well, the logic for messing with `uns` at a quick glance (like I said) seems to be coming from the [function that removes categories](https://github.com/scverse/anndata/blob/a4786471ee4d4e894fec150e426c3551db0f31e0/anndata/_core/anndata.py#L1182-L1204).  These lines are what Philipp posted and you can now turn this function off from `0.11.0` on:

https://github.com/scverse/anndata/blob/a4786471ee4d4e894fec150e426c3551db0f31e0/anndata/_core/anndata.py#L417-L419

**Comment by ilan-gold** [comment]
Just confirmed! Add
```python
import anndata as ad
ad.settings.remove_unused_categories = False
```
to your code on this repo's `main` branch and you should have your categories.

**Comment by flying-sheep** [comment]
Great! I think we can close this then. Just leave a comment if you feel otherwise!
