### ISSUE TITLE
all "nan"s in index due to obs column name and index name clash 

### ISSUE THREAD

**Issue by nadavyayon** [scverse/anndata#871]
"Its more a comment than a bug"

Saving an h5ad and reading it again resulted in losing the indices and getting them all replaced by "nan"s. I also got the "Transforming to str index." message when reading the file.  

I found out that I had a column in my `adata.obs` that had the same name "barcode" as my index resulting in this clash. droppping/renaming that column solved it!

This is one of these cases where you spend hours not understanding what's going on only to realize you made a stupid mistake but though of posting if an save agony for others in the future as I am not sure if it's a bug per se.

Thanks for maintaining this great resource!

**Comment by ivirshup** [comment]
Thanks for the info. 

I'm actually not too sure what's going on here. Could you share some version information and tell me a bit about the values in `"barcodes"`?
