### ISSUE TITLE
Horizontally concat AnnData Objects

### ISSUE THREAD

**Issue by gregjohnso** [scverse/anndata#876]
I might be useful to be able to perform a function like:

```
adata1 = adata[:, :n]
adata2 = adata[:, n:]

adata_cat = anndata.hstack([adata1, adata2])

```

**Comment by ivirshup** [comment]
I believe this should be covered by `anndata.concat([adata1, adata2], axis=1)`, see the [page on concatenation](https://anndata.readthedocs.io/en/latest/concatenation.html) and the [docstring for `concat`](https://anndata.readthedocs.io/en/latest/generated/anndata.concat.html#anndata.concat) for more details.

Let me know if that doesn't cover what you're trying to do.
