### ISSUE TITLE
AnnData.raw is returning Nonetype (for HLCA)

### ISSUE THREAD

**Issue by MohammedZidane** [scverse/anndata#880]
Hi,
I downloaded HLCA data and gave it a variable name adata_all, then ran the following command

print('type of adata_all.raw:', type(adata_all.raw))
adata = adata_all.raw.to_adata()

I got this error

type of adata_all.raw: <class 'NoneType'>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_366/1676474538.py in <module>
      1 print('type of adata_all.raw:', type(adata_all.raw))
----> 2 adata = adata_all.raw.to_adata()
      3 adata = remove_sparsity(adata)
      4 source_adata = adata
      5 target_adata = query_data

AttributeError: 'NoneType' object has no attribute 'to_adata'

Thanks

**Comment by Zethson** [comment]
Does the object have data in the raw slot? @LisaSikkema

**Comment by LisaSikkema** [comment]
Hi @MohammedZidane , where did you download the object from?

**Comment by MohammedZidane** [comment]
Hi lisa,
I downloaded it from 

https://docs.scvi-tools.org/en/stable/tutorials/notebooks/query_hlca_knn.html

**Comment by LisaSikkema** [comment]
I see, that is actually just the embedding of the data, it doesn't have the raw counts. You can download the full HLCA from e.g. cellxgene, for all relevant links see the HLCA homepage: 
https://github.com/LungCellAtlas/HLCA
It also has other information about the HLCA that might be helpful for you. Let me know if that works!

**Comment by ivirshup** [comment]
It looks like this issue has been resolved. Let me know if that's not the case!
