### ISSUE TITLE
Loss of data when loading `AnnData` object with duplicated `.obs` column names from `.h5ad` 

### ISSUE THREAD

**Issue by andrew-benz** [scverse/anndata#884]
The following snippet demonstrates the issue:
```py
import anndata as ad
import scanpy as sc
import numpy as np
import pandas as pd

adata = ad.AnnData(X=np.ones((2, 2)), dtype=np.float64)
adata.obs = pd.DataFrame(
    data=np.random.normal(size=(2, 2)),
    columns=['a', 'a'],
    index=['1', '2'],
)

adata.write_h5ad('test.h5ad')
adata_load = sc.read_h5ad('test.h5ad')
```
Then `adata.obs` will be something like
```
	        a	       a
1	-0.615750	0.524092
2	-0.004393	0.542863
```
while `adata_load.obs` looks like
```
  a a
1 a a
2 a a
```
Having an `AnnData` object with duplicated `.obs` column names is clearly an edge case, so perhaps the easiest fix is just to have `write_h5ad()` to throw an error when this happens?

Version information, in case it's relevant:

```py
>>> (ad.__version__, sc.__version__, np.__version__, pd.__version__)
('0.8.0', '1.9.1', '1.23.5', '1.5.3')
```

**Comment by ivirshup** [comment]
Thanks for the report! I've also just run into this while writing up the specifications. 

Would you be up for making a PR to add this error? The change would need to happen here:

https://github.com/scverse/anndata/blob/50b1b105ef32fd8bca91194b5fd07d250d18b4bf/anndata/_io/specs/methods.py#L502-L527

And would just include checking that the column names are unique.

I think it may be okay to have the index share a name with a column, but only if the values are the same. This wouldn't necessarily need to be addressed in the PR about unique column names.

**Comment by flying-sheep** [comment]
Maybe we should just raise an Exception if someone tries to create duplicate column names?

I’d think that having multiple columns with the same name is a case for `obsm`
