### ISSUE TITLE
Aggregating/Writing multiple AnnData objects in the same object/file

### ISSUE THREAD

**Issue by LeroyAdrien** [scverse/anndata#892]
Hi, many thanks for having created this wonderful project which is AnnData. 

I'm using your module to store information both on single cell and spatial transcriptomics data and working on functions to describe some links they share. 

To facilitate communication with other lab members I'd like to store my two experiments onto the same object. 

After having tried to merge them in a MuData object I realize that this is not ideal, as they do not represent different modalities of the same observations like in the standard mudata usecase (although being able to access the two objects like a dictionary is quite handy). 

Would you recommend a way to aggregate AnnData objects in a manner that is similar to mudata for which the nature of observations are different ? 

Thank you very much for the help

**Comment by ivirshup** [comment]
Thanks for opening this issue. Maybe @gtca could offer some thoughts. I think the unpaired observations is a use case for MuData that's being explored.

Could you say a bit more about how these experiments are linked and what you're trying to do with them?

**Comment by gtca** [comment]
Thanks for reaching out, @LeroyAdrien!

Indeed, it might be helpful to learn more about the relationship between the single-cell sequencing dataset and the spatial transcriptomics one. 
If this is the setting of e.g. [cell2location](https://www.nature.com/articles/s41587-021-01139-4) with no joint observations, standard MuData might be not the right data container for the task. However if the features are linked here, a MuData [with an alternative shared axis](https://mudata.readthedocs.io/en/latest/notebooks/axes.html) might be useful here: `MuData({"sc": adata_sc, "st": adata_st}, axis=1)`.

**Comment by LeroyAdrien** [comment]
What we are trying to achieve closely do resemble algorithms such as [novospark](https://www.nature.com/articles/s41596-021-00573-7), and as such, the features of the single cell and the spatial transcriptome should be identical.
Overall I think providing a shared axis might be the best solution. With the added benefit on staying in the scverse ecosystem.

Thank you very for the fast answer ! 

Best,

Adrien
