### ISSUE TITLE
concatenate multiple h5ad files in one

### ISSUE THREAD

**Issue by dhairya02** [scverse/anndata#913]
Hi, I am trying to concatenate multiple h5ad files into one but I get an error saying `ValueError: only one regex group is supported with Index`.
I have multiple h5ad files with varying n_obs × n_vars. Here is my code:

```py
adatas = [an.read_h5ad(filename) for filename in filenames]
batch_names = []
for i in range(len(adatas)):
  adatas[i].var_names_make_unique()
  batch_names.append(filenames[i].split('.')[0])
  print(i,adatas[i])

adata = adatas[0].concatenate(adatas[1:],
                              batch_key = 'ID',
                              uns_merge="unique",
                              index_unique=None,
                              batch_categories=batch_names)
```

and this produces the above error. Can anyone help?

**Comment by ivirshup** [comment]
Sorry for the late response.

I believe this will be fixed by using [`anndata.concat`](https://anndata.readthedocs.io/en/latest/generated/anndata.concat.html#anndata.concat) instead of `AnnData.concatenate`

**Comment by flying-sheep** [comment]
I’m closing this since there was no response. If you run into problems with `concat` as well, please open a new issue.
