### ISSUE TITLE
Differences between .X, .raw.X, and .raw in anndata object

### ISSUE THREAD

**Issue by pmarzano97** [scverse/anndata#936]
Hello world!
I have a question about the different layers of an anndata object (== adata).

What is the difference between **.X**, **.raw.X**, and **.raw**? Are .raw.X and .raw the same?

After the QC step, I always create a layer (== raw_counts) in my adata saving the raw counts before norm and log the counts: without any further step, this layer is equal to all the three above (raw.X, .X, and .raw), right?

After the layer creation, I run these three lines:
_sc.pp.normalize_total(adata, target_sum = 1e4)_
_sc.pp.log1p(adata)_
_adata.raw = adata_

Now, in **.raw.X** (or **.raw**?) I have the normalized and log-norm counts, correct?
While in **.X**, do I still have the raw raw counts or the norm ones?

I believe that the order by which I use the line _adata.raw = adata_reduced_ is crucial to overwrite or not a layer of information in the anndata object, am I wrong thinking this?
Is it correct to run it after the norm and log since I create the raw_counts layer, or should I run it before the norm and log?  

Lastly, is there a way to check if my counts are norm and log-norm?

Thanks all!!

**Comment by ivirshup** [comment]
Hey, I've responded to this question where you've asked it on the [discourse](https://discourse.scverse.org/t/differences-between-x-raw-x-and-raw-in-anndata-object/1192/2), so we can continue there
