### ISSUE TITLE
pytorch warnings

### ISSUE THREAD

**Issue by grst** [scverse/anndata#944]
Do we need warnings like this one
```
/home/sturm/anaconda3/envs/scirpy_dev/lib/python3.9/site-packages/anndata/experimental/pytorch/_annloader.py:18: UserWarning: Сould not load pytorch.
  warnings.warn("Сould not load pytorch.")
```
on `import anndata` even when I don't intend to work with pytorch? 

If pytorch is installed, I think it complains about not finding a GPU. 

**Version**
0.9rc1

**Comment by ivirshup** [comment]
Yeah. I've removed that on `main`: 

* https://github.com/scverse/anndata/pull/933

**Comment by ivirshup** [comment]
> If pytorch is installed, I think it complains about not finding a GPU.

I haven't done anything for this.

Is there something we should do?
