### ISSUE TITLE
Compatibility with `GenomicRanges`

### ISSUE THREAD

**Issue by jkanche** [scverse/anndata#952]
Hello team! 

This is more of a discussion topic to identify opportunities for collaboration. 

I am working on a set of packages to bring standard Bioconductor data structures to Python - [BiocPy](https://github.com/BiocPy). Pandas has limited support for genomic interval based operations, hence I developed [GenomicRanges](https://github.com/BiocPy/GenomicRanges) to support [interval based operations](https://biocpy.github.io/GenomicRanges/) from its equivalent Bioconductor package. 

AnnData is really awesome for single-cell analysis and `GenomicRanges` would complement the functionality `AnnData` and the scverse ecosystem provide. I would love to figure out how we can make `GenomicRanges` compatible with `AnnData` (`var`).

**Comment by grst** [comment]
Dear @jkanche,

thanks for your response!

Could you elaborate a bit more what benefits GenomicRanges provides over pre-existing Python libraries for ranged operations such as [bioframe](https://github.com/open2c/bioframe) and [pyranges](https://github.com/biocore-ntnu/pyranges)? In particular pyranges seems quite mature and as far as I can tell provides most (all?) of the operations you were describing.

Additionally, I was wondering about the scope of BiocPy. Do you see this mostly as a library that enables interoperability between the R/Bioconductor and the Python/scverse world, or do you envisage more Bioconductor packages being ported to Python that will make direct use of the Biocpy datastructures?
