### ISSUE TITLE
Systematically increasing coverage

### ISSUE THREAD

**Issue by falexwolf** [scverse/anndata#97]
I think it's time to systematically increase coverage so that we start approaching getting a bit closer to 100%.

I'll work on this in free slots, @Koncopd, feel welcome to do so, too! 🙂

**Comment by Koncopd** [comment]
Yep.

**Comment by falexwolf** [comment]
Forgot to paste the link to current coverage state: https://codecov.io/gh/theislab/anndata/src/a0cd0c62bc0ae792955cd90a9f5f55d093a08743/anndata/base.py 🙈 Wasn't a very useful issue definition without it... :wink:

**Comment by flying-sheep** [comment]
I think we succeeded at that
