### ISSUE TITLE
Adding "_reader" and "_writer" arguments sometimes causes errors

### ISSUE THREAD

**Issue by dcsynteny** [scverse/anndata#995]
In `anndata/_io/specs/registry.py`, in `Reader.read_elem` there's a line

```
read_func = partial(read_func, _reader=self)
```

but sometimes `read_func` does not have a `_reader` argument, and when it's called directly (rather than via the callback) immediately below, it triggers an exception. This happens for example when `read_func` is `read_dataframe`. There's a similar issue with `Writer.write_elem` and `_writer` arguments. 

The fix could be something like the below, but you might be able to think of something more elegant:

```
import inspect
...
if self.callback is not None or "_reader" in inspect.getfullargspec(read_func).args:
    read_func = partial(read_func, _reader=self)
```

**Comment by ivirshup** [comment]
Hey @dcsynteny, sorry about the late response here!

The `_reader` and `_writer` arguments (as well as the `Reader` class) are intended to be private, so I'm not sure if this should be considered a bug. How are you using these, and what are you trying to do?

**Comment by ivirshup** [comment]
No worries. I would be interested in hearing what you were using that for! Still working on how to expose some more of the internals beyond `read_dispatched`
